param(
    [string]$DocsRoot = 'docs/NPSPEC/Boot',
    [string]$OutputFile = 'build/bootmanager-npspec-coverage.md'
)

$ErrorActionPreference = 'Stop'
$root = (Resolve-Path -LiteralPath $DocsRoot).Path
$files = Get-ChildItem -LiteralPath $root -Recurse -File -Filter '*.md' | Sort-Object FullName

$evidenceRules = @(
    @{ Pattern = 'NPSPEC-BOOTCONTROL-LISTITEM-0001'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c/main.c: heapfreies typisiertes ListItem mit Titel, Subtitle, Status, stabiler ID/Reihenfolge, Normal/Hover/Focus/Selected/Disabled/Pressed/Error, Theme-Rundung, eindeutiger Auswahlmarkierung, Icon-/Label-Komposition und Accessibility; Haupt-, Settings-, Diagnose-, Power-, Firmware- und Hilfelisten nutzen es produktiv mit Maus, Tastatur, Space und Kontextmenü; Touch/Doppelklick, Item-Motion und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-LIST-0001'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c/main.c: feste indexierbare 64er Item-Collection im 128er Control-Pool mit stabiler Reihenfolge, Add/Remove, None/Single/Multi, O(1)-Direktauswahl, Fokus, sichtbarem Virtualisierungsfenster und ScrollView-Kopplung; produktive Bootmanager-Listen unterstützen Pfeile, Home/End, Page Up/Down, Enter/Space, Maus und QEMU-Nachweis; Touch/Controller, sehr große Providerlisten, Insert/Remove-Motion und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-LABEL-0001'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c/text.c: heapfreies Label-Control mit neun Typen, neun horizontal/vertikal kombinierten Ausrichtungen, Ein-/Mehrzeile, Wrap/Ellipsis, dynamischem UTF-8-Text, Theme-/Statusfarben und DPI-Skalierung; Wortmarke und Statuszeile nutzen es produktiv, Host- und QEMU-Nachweise vorhanden; relationale Beschriftung, Motion und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-ICON-0001'; Status = 'Teilweise integriert'; Evidence = 'controls.c/icons.c/ui.c: heapfreies semantisches Icon-Control mit validierten zentralen Token-Ressourcen, proportionaler DLU-Skalierung, Theme-/Disabled-/Statusfarben und dekorativ/semantischer Accessibility; alle sechs sichtbaren Menü-/Tile-Icons nutzen es produktiv, Host- und QEMU-Nachweis vorhanden; allgemeiner SVG-Primärpfad, Motion und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-IMAGE-0001'; Status = 'Teilweise integriert'; Evidence = 'controls.c/branding.c/resources.c/ui.c: heapfreies Image-Control mit Original/Stretch/Fit/Fill/Center, Clipping, Alpha-Coverage, Tint und zentral wiederverwendeter validierter NovaOS-Logo-Ressource; das Branding nutzt produktiv Fit und Theme-Tint, Host- und QEMU-Nachweis vorhanden; weitere PNG/BMP/QOI/SVG-Decoder bleiben durch fehlendes BAP-/Index-Wire-Format blockiert, Motion und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-SEPARATOR-0001'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c: nicht-interaktives heapfreies Separator-Control mit horizontaler/vertikaler Ausrichtung, optionalem zentriertem Titel, Theme-Linie und dekorativer Accessibility; die Settings-Gruppen werden produktiv horizontal getrennt, Host- und QEMU-Framebuffer-Nachweis vorhanden; Icon-Variante, Theme-Fade und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-BUTTON-0001'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c/dialog.c: heapfreies Button-Control mit sieben validierten Typen, Text/Icon, Aktion, Pressed-/Toggle-/Busy-Schutz, exakt-einmal-Auslösung, Theme, Rundung, Fokus und Accessibility; Dialogaktionen verwenden produktiv Primary/Secondary/Destructive Buttons, Host- und QEMU-Dialogtests sind grün; Touch/Controller, vollständige Motion und gemeinsame BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-MENUBUTTON-0001'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c/main.c: heapfreier Menu Button mit validierter 1:1-Menübindung, Collapsed/Expanded, Pfeilindikator, Safe-Area-Overlay und Fokus-Rückgabe; die Theme-Auswahl verwendet ihn produktiv mit Maus, Enter/Space, Pfeilen, Home/End, Escape/Links und drei Theme-Aktionen; Hosttests sowie QEMU-Marker/Framebuffer-Nachweis vorhanden; Touch/Controller, Arrow-Motion, Untermenüs und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTRESOURCE-0002'; Status = 'Blockiert'; Evidence = 'BAP beschreibt Inhalte semantisch, definiert aber kein normatives Wire-Format: Magic-Wert, Headergröße, Feldoffsets/Endianness und Gesamtprüfsummenverfahren fehlen' },
    @{ Pattern = 'NPSPEC-BOOTRESOURCE-0003'; Status = 'Blockiert'; Evidence = 'Resource-Index-API ist beschrieben, aber binäre Packung, Hash-/ID-Ableitung, Tabellenheader und Kollisionsverfahren sind nicht normativ festgelegt' },
    @{ Pattern = 'NPSPEC-BOOTRESOURCE-0001'; Status = 'Teilweise integriert'; Evidence = 'resources.c: zentraler heapfreier Manager mit 128er Objektpool und 256er Open-Addressing-Hashindex für O(1)-URI/ID-Lookup. Modell und Lifecycle enthalten unveränderlichen Namen/ID, Typ, Version, Größe, CRC32, Herkunft, Zustand, Adresse, Referenzen, Fallback, Priorität und bis zu acht Abhängigkeiten. Lazy/Preload, CRC vor Registrierung und jeder Nutzung, Cache-Hit/Miss, transitive Referenzen, Zyklenschutz, 8-MiB-Budget/LRU-Eviction, Unload und Shutdown sind typisiert. Font, Icons, Themes, Design und Logo werden zentral registriert und vor dem ersten UI-Frame verifiziert/preloaded. Hosttests belegen Abhängigkeit, Zyklus, beschädigte Primärressource mit Fallback, LRU, Busy-Unload, Background-Abweisung, Preload und Shutdown. OVMF/QEMU meldet RESOURCE-LOADER-READY und RESOURCE-PRELOAD-READY. Externe Packages, Signaturen und Paketstruktur bleiben durch die fehlenden Wire-Formate in 0002/0003 blockiert; echte Ladezeitmessung, persistente Packageherkunft und BIOS-C-Pipeline-Parität fehlen' },
    @{ Pattern = 'NPSPEC-BOOTRESOURCE-0004'; Status = 'Teilweise integriert'; Evidence = 'resources.c/ui.c: typisierter Resource Loader mit Lazy und synchronem Preload, Prioritätsreihenfolge Critical/High/Normal/Low, O(1)-Index/Cache, fester Registry ohne Hotpath-Allokation, CRC-/Typ-/Version-/Größenprüfung, mehrfacher Ladeunterdrückung, Referenzzählung, automatischer transitiver Abhängigkeitsauflösung, Zyklusdetektion, Default-Fallback, Budget/LRU und deterministischem Unload. Optionales Background Loading wird explizit UNSUPPORTED statt scheinimplementiert. Produktiv werden alle eingebetteten GUI-Assets bis Normal vor Verwendung verifiziert; QEMU bootet damit alle Menüframes. Package Reader, Indexdescriptor-/Offsetprüfung und Dekompression aus externen BAPs können ohne 0002/0003-Wire-Format nicht implementiert werden; echte parallele Anfragen, asynchrones Background Loading, Loader-Dispatcher pro Packageformat, Lade-/Dekompressionszeitmessung und gemeinsame BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTRESOURCE-0005'; Status = 'Teilweise integriert'; Evidence = 'compression.c/resources.c/ui.c: transparenter heapfreier Resolver für NONE und verpflichtendes LZ4-Raw-Blockformat mit O(n)-Decoder, vollständigen Längen-/Offset-/Grenz-/Überlaufprüfungen, überlappenden Matches, exakter Ausgabegröße und typisierten Fehlern; optionales Zstd wird explizit UNSUPPORTED gemeldet. Der Resource Loader prüft CRC32 der gepackten Daten vor, entpackt beim ersten Zugriff in einen statischen 512-KiB-Blockpool, prüft Größe und CRC32 danach, cached genau eine dekodierte Kopie und evicted prioritäts-/LRU-basiert unter Pooldruck. Fehler aktivieren verifizierte Fallbacks. Diagnosen erfassen Verfahren, Größen, Verhältnis, Aufrufe, Dekompressionen, Fehler und Poolverbrauch. Hosttests belegen NONE, LZ4-Literal/Match/Overlap, beschädigten/trunkierten Stream, Größenfehler, Zstd-Abweisung, Lazy Loading, Cache-Wiederverwendung, Fallback und Poolgrenze. OVMF/QEMU dekodiert beim realen Start eine gepackte Probe und meldet RESOURCE-LZ4-DECODE-READY. Externe BAP-/Indexanbindung bleibt mangels normativem Wire-Format in 0002/0003 blockiert; Zstd, Zeitmessung, größere Ressourcen als der statische Pool und gemeinsame BIOS-C-Pipeline fehlen' },
    @{ Pattern = 'NPSPEC-BOOTRESOURCE-0006'; Status = 'Teilweise integriert'; Evidence = 'integrity.c/resources.c/ui.c: heapfreier Integritätsmanager mit CRC32, vollständigem SHA-256, konstantzeitlichem Digestvergleich, Trust Unknown/Valid/Signed/Invalid/Corrupted und Richtlinien Permissive/Standard/Strict. Headerähnliche Metadaten werden auf ID, Typkontext, Version, Datenzeiger, Größe, Pointerüberlauf und Signaturstatus geprüft. Der Loader validiert gepackte Daten vor Dekompression sowie Originalgröße, CRC32 und optional SHA-256 danach, speichert Trust O(1) an der Ressource und überspringt erneutes Hashing nur bei weiterhin gecachten validierten Daten. Ungültige Daten/Signaturzustände werden verworfen und nutzen den typisierten Fallback; Abhängigkeiten und Zyklen prüft der Loader transitiv. Hosttests belegen FIPS-SHA-256-abc, CRC/SHA, alle drei Richtlinien, ungültige und vorgelagert verifizierte Signaturzustände, Korruption, Fallback und Cache-Skip. OVMF/QEMU prüft feste SHA-256-Werte einer gepackten und dekodierten LZ4-Ressource und meldet RESOURCE-SHA256-VERIFIED. Kryptografische Ed25519/ECDSA-Verifikation, Schlüssel-/Signatur-Wire-Format, Paket-/Indexheader und Manifestauthentizität sind ohne BOOTSECURITY-0001 sowie normative 0002/0003-Formate nicht implementierbar; SHA-512, Zeitmessung und BIOS-C-Parität fehlen' },
    @{ Pattern = 'NPSPEC-BOOTRESOURCE-0007'; Status = 'Teilweise integriert'; Evidence = 'image_renderer.c/resources.c/ui.c: plattformneutraler heapfreier PNG-1.2-Decoder mit öffentlicher Initialize/Validate/Decode-API, statischem 240-KiB-Decodepuffer und 512-KiB-RGBA-Pixelpool. Unterstützt werden verpflichtend Grayscale, RGB, RGBA und Indexed in 1/2/4/8 Bit sowie optional Grayscale+Alpha 8 Bit; Ausgabe ist premultipliziertes RGBA32. PLTE und tRNS für Palette, Grayscale und RGB, mehrere zusammenhängende IDAT-Chunks, Stored/Fixed/Dynamic Deflate, Adler32 und alle Filter None/Sub/Up/Average/Paeth sind implementiert. Parser prüft Signatur, IHDR-first, Chunknamen/Reserved Bit, Längen/Überläufe, CRC jedes Chunks, PLTE/tRNS/IDAT/IEND-Reihenfolge, unbekannte Critical Chunks, exaktes IEND und Dimensionen vor Allokation. Hosttests belegen sämtliche Farbtypen, Packed 1/2 Bit, Alpha/tRNS, Multi-IDAT, alle fünf Filter, Deflatevarianten, CRC-Schaden, Interlace-Abweisung und Validierungsdiagnose. OVMF/QEMU lädt und prüft eine echte 1-Bit-Grayscale/tRNS-PNG-Ressource und meldet PNG-DECODER-READY. Optionales 16 Bit und Adam7, unbegrenzt viele IDATs, Decodezeitmessung, externer BAP-Pfad und gemeinsame BIOS-C-Pipeline fehlen' },
    @{ Pattern = 'NPSPEC-BOOTRESOURCE-0008'; Status = 'Blockiert'; Evidence = 'Die SVG-Spezifikation verlangt ausdrücklich NPSPEC-BOOTRENDER-0012 Transformations/Alpha und NPSPEC-BOOTRENDER-0013 Vector Geometry. Im Dokumentbestand fehlt 0013 vollständig; die Datei 0012 ist in Inhalt und eigener Dokument-ID eine Kopie von 0011 2D Transformations und definiert keinen Alpha-/Vektorvertrag. BOOTRESOURCE-0008 selbst nennt Elemente und Attribute, legt aber weder Path-Kommandountermenge, Fill-/Winding-Regel, Stroke Caps/Joins, Kurven-/Arc-Flattening, XML-Namespace-/Entityregeln noch eine Syntax für Themefarbreferenzen fest. Eine Implementierung könnte daher nicht nach den Akzeptanzkriterien auf korrekte Geometrie und identische BIOS-/UEFI-Pixel geprüft werden. Die vorhandenen zentralen 2-Bit-AA-Icons bleiben als sichere produktive Alternative aktiv; ein angeblich normativer SVG-Parser wird nicht erfunden' },
    @{ Pattern = 'NPSPEC-BOOTTEXT-0003'; Status = 'Teilweise integriert'; Evidence = 'unicode.c/text.c: validierender UTF-8-Decoder bis U+10FFFF, Overlong-/Surrogat-Abweisung, U+FFFD-Missing-Glyph, UTF-8-Umlaute, Block-/Fehlertests und Diagnose; internationale Glyphatlanten fehlen' },
    @{ Pattern = 'NPSPEC-BOOTDESIGN-0009'; Status = 'Teilweise integriert'; Evidence = 'icons.c/ui.c: alle 15 semantischen O(1)-Tokens besitzen zentral registrierte, geprüfte 2-Bit-AA-Ressourcen; Unterseiten verwenden eigene Tokenzuordnungen, DLU-Skalierung, Theme-Tint, Cache-Diagnose und ausschließlich einen Fallback für ungültige externe Tokens; allgemeiner SVG-Renderer und BIOS-Parität der neun erweiterten Symbole fehlen' },
    @{ Pattern = 'NPSPEC-BOOTDESIGN-0002'; Status = 'Teilweise integriert'; Evidence = 'theme.c: validierte statische O(1)-Token-Tabellen für Farben, Abstände, Radien, Transparenz, Material und Motion-Overrides; Typography-/Shadow-Registry noch nicht vollständig' },
    @{ Pattern = 'NPSPEC-BOOTDESIGN-0003'; Status = 'Teilweise integriert'; Evidence = 'theme.c/ui.c: sämtliche UEFI-Farben über semantische Rollen, deterministischer Kontrasttest, Focus/Selected/Disabled/Statusfarben und Accessibility-Overrides; BIOS nutzt weiterhin eigene äquivalente Tokenquelle' },
    @{ Pattern = 'NPSPEC-BOOTDESIGN-0012'; Status = 'Teilweise integriert'; Evidence = 'UEFI und BIOS: Dark Theme; UEFI aus zentral validierter Token-Tabelle mit dynamischen Controls, Icons, Branding, Fokus und Materialien; allgemeine externe Theme-Resource fehlt' },
    @{ Pattern = 'NPSPEC-BOOTDESIGN-0013'; Status = 'Teilweise integriert'; Evidence = 'theme.c: vollständiger statischer Light-Token-Satz; QEMU-Wechsel und visueller Framebuffer-Nachweis; BIOS-Light-Theme fehlt' },
    @{ Pattern = 'NPSPEC-BOOTDESIGN-0014'; Status = 'Teilweise integriert'; Evidence = 'theme.c: High Contrast mit opaken Flächen, Rahmen, gelbem Fokus, weißen Texten, Reduced Motion und Materialfallback; QEMU-Wechsel und visueller Nachweis; Screenreader fehlt' },
    @{ Pattern = 'NPSPEC-BOOTDESIGN-0015'; Status = 'Teilweise integriert'; Evidence = 'BIOS und UEFI verwenden dieselbe generierte 2-Bit-AA-NovaOS-Bildmarke, Nova-Blau und Wortmarke; UEFI Bootmanager spiegelt den Kopf spezifikationsgemäß nach rechts; vollständige visuelle BIOS/UEFI-Parität aller Themes fehlt' },
    @{ Pattern = 'NPSPEC-BOOTRESOURCE-0011'; Status = 'Teilweise integriert'; Evidence = 'Dark-, Light- und High-Contrast-Deskriptoren sind als geprüfte Theme-Ressourcen zentral registriert; externer BAP-Loader bleibt durch fehlendes Wire-Format blockiert' },
    @{ Pattern = 'NPSPEC-KERNELLOADER-0001'; Status = 'Integriert'; Evidence = 'boot2.asm: NKI-bevorzugte Erkennung sowie validiertes direktes ELF32-/ELF64-Laden; QEMU-Positiv- und Negativtests' },
    @{ Pattern = 'NPSPEC-KERNELENTRY-0001'; Status = 'Teilweise integriert'; Evidence = 'boot2.asm und kernel: definierter NBHP/BIB-Registerübergang und frühe Kernelvalidierung; UEFI-Kernelübergang fehlt' },
    @{ Pattern = 'NPSPEC-BOOT-0001-N'; Status = 'Teilweise integriert'; Evidence = 'BIOS Stage 1/2, versioniertes NBHP/BIB, NKI/ELF-Fallback, Fehlerpfade und erster UEFI-Plattformpfad' },
    @{ Pattern = 'NPSPEC-BOOTERROR-0001'; Status = 'Teilweise integriert'; Evidence = 'Einheitlicher Nova-Fehlerbildschirm für Boot- und Kernel-Fehler; vollständige Recovery-Backends fehlen' },
    @{ Pattern = 'NPSPEC-BOOTFS-0001'; Status = 'Teilweise integriert'; Evidence = 'Sektorbasierter read-only Kernelzugriff vorhanden; Dateisystemtreiber-Registry und NovaFS fehlen' },
    @{ Pattern = 'NPSPEC-BOOTGRAPHICS-0001'; Status = 'Teilweise integriert'; Evidence = 'BIOS-Framebuffer-Renderer und UEFI-GOP-Grundpfad; gemeinsame plattformneutrale Runtime fehlt' },
    @{ Pattern = 'NPSPEC-BOOTHANDOFF-0001'; Status = 'Teilweise integriert'; Evidence = 'TLV-basiertes NBHP/BIB wird im BIOS-Pfad aufgebaut und vom Kernel validiert; UEFI-Handoff fehlt' },
    @{ Pattern = 'NPSPEC-BOOTMANAGER-0001'; Status = 'Teilweise integriert'; Evidence = 'BIOS Bootmanager-Runtime, Entries, Auswahl und sichere Fallbacks; persistente Entry-Quellen fehlen' },
    @{ Pattern = 'NPSPEC-BOOTMEMORY-0001'; Status = 'Teilweise integriert'; Evidence = 'Statische Speicherbereiche, Grenzen und lokaler Schreibtest; allgemeine Memory-Map-/Pool-Runtime fehlt' },
    @{ Pattern = 'NPSPEC-BOOTPLATFORM-0001'; Status = 'Teilweise integriert'; Evidence = 'BIOS- und getesteter UEFI-GOP-Einstieg vorhanden; einheitliche Plattform-vtable fehlt' },
    @{ Pattern = 'NPSPEC-BOOTSTAGE1-0001'; Status = 'Integriert'; Evidence = 'boot1.asm: deterministischer 512-Byte-Stage-1-Lader mit Signatur, Fehlerpfad und fester Stage-2-Grenze' },
    @{ Pattern = 'NPSPEC-BOOTSTAGE2-0001'; Status = 'Teilweise integriert'; Evidence = 'boot2.asm: Loader, GUI, Diagnose und Handoff; modulare Ressourcenauslagerung ist durch BAP-Wire-Format blockiert' },
    @{ Pattern = 'NPSPEC-BOOTUI-0002'; Status = 'Teilweise integriert'; Evidence = 'runtime.c/main.c/ui.c: zentraler heapfreier Single-Thread-Runtime-Core mit strikt validierter Subsystemreihenfolge Memory, Platform, Graphics, Diagnostics, Configuration, Resources, Scene, Layout, Motion, Input und Renderer; feste 32er Taskqueue priorisiert Critical, Input, Rendering, Animation, Layout, Background und Idle deterministisch. Jeder produktive UEFI-Frame durchläuft exakt Input, Event Queue, Control, Application, Motion, Layout, Dirty Detection, Render Queue, Rendering, Compositor, Present und Diagnostics; ausgelassene Phasen werden verworfen. Hosttests prüfen Reihenfolge, Scheduler und Fehlerfälle, QEMU belegt Running und abgeschlossene Frames. Eine vollständige gemeinsame BIOS-Runtime, Touch-/Controllerprovider und reale Hardware-Performancezeitmessung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTUI-0003'; Status = 'Teilweise integriert'; Evidence = 'runtime.c/main.c/ui.c: deterministischer Lifecycle Created, Initializing, Loading Resources, Building Scene, Layout, Ready, Running, Suspended, Recovery, Shutdown und Destroyed mit Abweisung ungültiger Transitionen, Eingabesperre in Suspend/Recovery sowie sicherem GUI-Fehlerübergang in Recovery/Textfallback. F6 auf Diagnose testet produktiv Suspend/Resume und zeichnet den Statusframe; Hosttests decken Recovery, Shutdown und Destroy ab, QEMU-Marker und Framebuffer belegen Lifecycle und sichtbaren Endzustand. Echtes Firmware-Suspend/Resume, Hotplug-/Controllerpfade und identische BIOS-Lifecycle-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTUI-0004'; Status = 'Teilweise integriert'; Evidence = 'state_model.c/runtime.c/ui.c: gemeinsamer heapfreier 256er Zustandskern für Runtime, Scene, Dialog, Overlay, Control, Focus, Pointer, Keyboard, Touch, Navigation, Page, Animation, Render, Resource, Theme und Error mit domänenspezifischen Übergangsmatrizen, eindeutigem Owner/Parent, atomarer Validierung, OnExit/OnTransition/OnEnter-Eventring, Zeitstempel, Transition-/Fehlerzählern, Checkpoint/Rollback/Reset, Hierarchieprüfung und versioniertem internem Snapshot samt Prüfsumme. Die Runtime nutzt ihn autoritativ; Framephasen werden als Input, Update, Animation, Layout, Render und Present synchronisiert. Hosttests prüfen Scene-Control-Hierarchie, verbotene Sprünge, Press/Release, Rollback, Restore, Korruption und Kind-vor-Eltern-Abbau; F6 und QEMU belegen den produktiven Ablauf samt Statusframe. Bestehende Dialog-, Page-, Navigation-, Motion-, Resource- und Input-Teilautomaten sind noch nicht vollständig auf den gemeinsamen Kern migriert; Touch/Controller und BIOS-Parität fehlen' },
    @{ Pattern = 'NPSPEC-BOOTUI-0005'; Status = 'Teilweise integriert'; Evidence = 'graphics.c/compositor.c/ui.c und uefi/graphics.c: gemeinsamer validierter GraphicsContext kapselt Width, Height, bytegenauen Pitch, BPP, DPI/Skalierung, PixelFormat, Front-/Backbuffer, Capabilities, Hardwaremetadaten und Diagnose. Rendering, Layout und Controls kennen kein GOP mehr; der Compositor arbeitet ausschließlich offscreen und GAL Present schreibt nur in der Runtime-Present-Phase bounds-geprüft und heapfrei in den sichtbaren Buffer. Konverter decken RGBA/BGRA8888, RGB/BGR888, RGB565 und beliebige Bitmasken ab; GOP RGB/BGR/Bitmask wird validiert, BltOnly abgewiesen. Hosttests prüfen Formatkanäle, Pitch größer als Width, ungültige Buffer und Present-Synchronisation; echter GPT/FAT32-Boot, Recovery und QEMU 800x600/1280x720/1920x1080 belegen den produktiven GOP-Pfad. BIOS/VBE verwendet noch seinen eigenen Renderer; Multi-GOP, Triple Buffer, QHD/4K, echte DPI-Hardwaremetrik und gemessene Zeitbudgets fehlen' },
    @{ Pattern = 'NPSPEC-BOOTUI-0006'; Status = 'Teilweise integriert'; Evidence = 'resolution.c/layout.c/graphics.c/main.c: zentraler gecachter DLU-Scaling-Kontext mit physischem und logischem Viewport, 1920x1080=100-Prozent-Referenz, zuverlässiger DPI- oder Auflösungsheuristik, automatischer und 1000..3000-Promille-Benutzerskalierung, XS/S/M/L/XL/XXL/Ultra-Klassen, 4:3/5:4/16:9/16:10/21:9/32:9/Custom-Erkennung, vierseitiger 3-Prozent-Safe-Area sowie deterministischem DLU-zu-Pixel- und Pixel-zu-DLU-Alignment. Berechnung erfolgt nur bei Start, Auflösungs-, DPI- oder Scalewechsel; Layout, Text, Icons, Radien, Dialoge und Motion-Distanzen verwenden denselben Scale. Hosttests decken 640x480 bis 3840x2160, QHD/UHD, UltraWide, 144 DPI, Override/Fallback und Constraints ab; QEMU belegt 800x600, 1280x720 und die korrigierte 1920x1080-Referenz mit GAL-Present. Sichtbare Scale-Auswahl in Settings, zuverlässige physische GOP-DPI, Multi-/Dual-Screen, BIOS-Parität und QEMU-QHD/UHD fehlen wegen der statischen 1920x1080-Compositorgrenze' },
    @{ Pattern = 'NPSPEC-BOOTUI-0007'; Status = 'Teilweise integriert'; Evidence = 'memory.c/ui.c/diagnostics.c: zentraler heapfreier Manager für Permanent/Runtime/Scene/Animation/Frame/Render/Cache/Diagnostics mit normativen Einzelbudgets und 64-MiB-Gesamtgrenze, getrennten statischen Arenen, O(1)-Bump-Allokation, 16-/64-Byte-Alignment, 256er Objektmetadaten, Owner, Referenzzählung, Pointer-/Double-Free-/Alignment-/Overflow-Erkennung, Peak/Fragmentierung und atomarem Frame-Reset. Der produktive Renderer reserviert und validiert Frame-Metadaten über den Manager; F8 zeigt den geprüften Zustand, Host erzwingt Cache-Overflow mit Safe Mode und QEMU belegt jeden Frame. Bereits ältere statische Subsystempools sind noch nicht vollständig migriert, UEFI-Seitenreservierung und BIOS-Parität fehlen' },
    @{ Pattern = 'NPSPEC-BOOTUI-0008'; Status = 'Teilweise integriert'; Evidence = 'recovery.c/ui.c/main.c: heapfreier Recovery Manager mit INFO/WARNING/RECOVERABLE/CRITICAL/FATAL, sieben deterministischen Eskalationsstufen, 32er Historie, Diagnoseevents, Feature-Isolation, Safe Mode, Textmodus, Continue-Boot-Invariante und sechs einmalig auslösenden Watchdogs. F10 auf Diagnose simuliert kritische Degradation mit verständlicher Statusmeldung; F9 prüft den fatalen Textfallback mit automatischem Fünf-Sekunden-Weiterstart. Hosttests und QEMU-Marker/Framebuffer belegen beide Pfade. Automatische Hooks für jeden einzelnen Renderer-/Resource-/Layoutfehler, echte GOP-Fehlerinjektion und BIOS-Parität fehlen' },
    @{ Pattern = 'NPSPEC-BOOTUI-0009'; Status = 'Teilweise integriert'; Evidence = 'configuration.c/ui.c/main.c: zentraler heapfreier Runtime-Manager mit Version 1.0.0, sicheren Defaults, expliziten Wertebereichen, interner Integritätsprüfsumme, O(1)-Key-Zugriff, atomarem Begin/Set/Commit, vollständigem Rollback, Reset, Generation/Benachrichtigung und getrennten temporären Overrides. Theme, Reduced Motion, Tooltips und 250..1500-ms-Verzögerung committen produktiv vor Anwendung; Hosttests prüfen Korruption und Transaktionen, Settings-/Theme-QEMU-Flows belegen mehrere Commits und sichtbare Endzustände. Das externe Binärformat bleibt nicht implementierbar definiert: Magic/Formatkennung, Headergröße, Feldoffsets, Endianness, Section-Typen, externer Prüfsummenalgorithmus und Migrationsabbildungen fehlen; deshalb wird keine inkompatible Persistenz erfunden' },
    @{ Pattern = 'NPSPEC-BOOTUI-0010'; Status = 'Teilweise integriert'; Evidence = 'design.c/ui.c/theme.c/resources.c/icons.c/motion.c: versioniertes Nova-Design-Manifest 1.0.0 mit FNV-Integrität, Major-Kompatibilitätsprüfung sowie gemeinsamen DLU-Tokens für Typografie, Komponenten, Motion, Glass und Schatten. Startvalidierung umfasst Dark/Light/High Contrast, Font, Logo und alle Iconressourcen; OEMs dürfen ausschließlich validierte Bild-/Animationsressourcen und opake Akzentfarben setzen. Hosttests prüfen Tokenwerte, Versionskonflikt, Ressourcen und OEM-Grenzen; QEMU durchläuft alle drei Themes und meldet DESIGN-COMPATIBILITY-READY. Ein nachweisbarer NovaOS-Desktop-Verbraucher, SVG-Primärpfad, externes gemeinsames Design-Token-Paket und vollständige BIOS-Parität fehlen; BAP/Index bleiben durch NPSPEC-BOOTRESOURCE-0002/0003 blockiert' },
    @{ Pattern = 'NPSPEC-BOOTUI-0001'; Status = 'Teilweise integriert'; Evidence = 'architecture.c/runtime.c/ui.c und die gekapselten Subsystemmodule: versioniertes Architekturmanifest für Platform, Resource, Graphics, Renderer, Scene, Layout, Motion, Controls, Navigation, Dialog, Application und Diagnostics mit expliziten Abhängigkeitsmasken, deterministischer Registrierung, Ready-Gate und Startvalidierung. Runtime und State Model erzwingen Lifecycle und Framepipeline; Hosttests weisen ungültige Reihenfolge ab, UEFI/QEMU meldet UI-ARCHITECTURE-READY. BIOS verwendet weiterhin seine platzoptimierte Parallelruntime; Touch, vollständiges Retained-Window-System, SVG/Blur, echte Hardware-Performancewerte und die geforderte Plattformmatrix außerhalb QEMU sind nicht vollständig belegt' },
    @{ Pattern = 'NPSPEC-BOOTUI-'; Status = 'Teilweise integriert'; Evidence = 'BIOS-Runtime mit DLU, Zuständen, Eingabe, Fehlerpfaden und Tokens sowie UEFI-GOP-Grundpfad; gemeinsame Runtime/Pools fehlen' },
    @{ Pattern = 'NPSPEC-BOOTMANAGER-UI-0001'; Status = 'Teilweise integriert'; Evidence = 'BIOS und UEFI: Control-basierte Hauptauswahl, Icons, sichtbarer Fokus, Tastatur/Maus, Statuszeile und sicherer Standardstart; Multi-Boot-Discovery, Touch und vollständiges Informationspanel fehlen' },
    @{ Pattern = 'NPSPEC-BOOTMANAGER-UI-0002'; Status = 'Teilweise integriert'; Evidence = 'boot2.asm: BM_VIEW_DETAILS, F2, Eigenschaften-/Statusansicht und Start-/Erweitert-Aktionen; Motion und Touch fehlen' },
    @{ Pattern = 'NPSPEC-BOOTMANAGER-UI-0003'; Status = 'Teilweise integriert'; Evidence = 'boot2.asm: BM_VIEW_ADVANCED, F3, fokussierbare Startmodusliste, Recovery-/Fallback-Aktionen; Kernelparametereditor fehlt' },
    @{ Pattern = 'NPSPEC-BOOTMANAGER-UI-0004'; Status = 'Teilweise integriert'; Evidence = 'BIOS und UEFI: navigierbares Recovery-Menü, sichere Nicht-verfügbar-Zustände und Rücknavigation; geprüfte schreibende Recovery-Module fehlen' },
    @{ Pattern = 'NPSPEC-BOOTMANAGER-UI-0005'; Status = 'Teilweise integriert'; Evidence = 'boot2.asm: Self-Healing-Systemstatus und sichere Sperre schreibender Reparaturen; NovaFS-Reparaturmodul fehlt' },
    @{ Pattern = 'NPSPEC-BOOTMANAGER-UI-0006'; Status = 'Teilweise integriert'; Evidence = 'boot2.asm: Snapshot-Ansicht mit leerem, erklärtem Zustand; NovaFS-Snapshot-Katalog fehlt' },
    @{ Pattern = 'NPSPEC-BOOTMANAGER-UI-0007'; Status = 'Teilweise integriert'; Evidence = 'boot2.asm: Speichertestansicht, AA55/55AA-Schnelltest, Ergebnis und Fortschritt; vollständiger physischer RAM-Test fehlt' },
    @{ Pattern = 'NPSPEC-BOOTMANAGER-UI-0008'; Status = 'Teilweise integriert'; Evidence = 'boot2.asm: read-only BIOS-Datenträgerstatus; GPT/MBR-, SMART- und Schreibmodule fehlen' },
    @{ Pattern = 'NPSPEC-BOOTMANAGER-UI-0009'; Status = 'Teilweise integriert'; Evidence = 'boot2.asm: Verschlüsselungsstatus und sicher deaktivierte Authentifizierung ohne verschlüsseltes Volume; Crypto-/TPM-Backend fehlt' },
    @{ Pattern = 'NPSPEC-BOOTMANAGER-UI-0010'; Status = 'Teilweise integriert'; Evidence = 'boot2.asm: Netzwerk-Boot-Status und erklärter No-Adapter/No-Server-Zustand; PXE-UNDI-/DHCP-Backend fehlt' },
    @{ Pattern = 'NPSPEC-BOOTMANAGER-UI-0011'; Status = 'Teilweise integriert'; Evidence = 'firmware.c/main.c/ui.c und boot2.asm: eigene UEFI-Firmwarestatusseite mit Hersteller, Revision, SecureBoot, SetupMode und OsIndicationsSupported; BootToFwUi wird nur bei gemeldeter Unterstützung nach zweistufiger Bestätigung per Runtime Services gesetzt und in QEMU bis zum Reset nachgewiesen; ein Runtime-Services-Mocktest belegt zusätzlich die sichere Sperre ohne Capability; TPM/SMBIOS/ACPI-Details und BIOS-Setupwechsel fehlen' },
    @{ Pattern = 'NPSPEC-BOOTMANAGER-UI-0014'; Status = 'Teilweise integriert'; Evidence = 'BIOS und UEFI: read-only Diagnoseansicht mit Übersicht, Hardware-, Boot-, Speicher- und Ereignisbereichen; vollständige Hardwareprovider und Berichtsexport fehlen' },
    @{ Pattern = 'NPSPEC-BOOTMANAGER-UI-0015'; Status = 'Teilweise integriert'; Evidence = 'BIOS und UEFI: Energieauswahl mit expliziter zweiter Bestätigung; UEFI Shutdown/Restart über Runtime ResetSystem, sichere Sperre nicht verfügbarer Recovery-/Firmware-/Netzwerkziele; Touch fehlt' },
    @{ Pattern = 'NPSPEC-BOOTMANAGER-UI-0016'; Status = 'Teilweise integriert'; Evidence = 'BIOS und UEFI: sichtbarer, sekündlich aktualisierter Fünf-Sekunden-Countdown, Abbruch durch Eingabe und sicherer Standardstart; persistente Konfiguration fehlt' },
    @{ Pattern = 'NPSPEC-BOOTMANAGER-UI-0018'; Status = 'Teilweise integriert'; Evidence = 'BIOS und UEFI: F1-Hilfe, lokale Bedienhinweise, ESC-Rücknavigation und Fokuswiederherstellung; UEFI ergänzt einen festen lokalen Acht-Themen-Index, UTF-8-Suche, gefilterte Ergebnisnavigation, kontextbezogene Detaildialoge und QEMU-Nachweis; vollständige Lokalisierungsressource, Touch und BIOS-Suchparität fehlen' },
    @{ Pattern = 'NPSPEC-BOOTINPUT-'; Status = 'Teilweise integriert'; Evidence = 'BIOS: PS/2-Tastatur/Maus; input.c: gemeinsame O(1)-Eventqueue, Pointer Capture/Hit-Test, Fokus, Shortcuts und Repeat; UEFI: Tastatur und Simple Pointer mit Cursor, Auswahl, Klickaktion und Countdown-Abbruch; QEMU weist Pointer-Protokoll und Tastaturnavigation nach, headless HMP-Mausinjektion und Touch fehlen' },
    @{ Pattern = 'NPSPEC-BOOTLAYOUT-0001'; Status = 'Teilweise integriert'; Evidence = 'layout.c/ui.c: heapfreie Measure-/Arrange-/Finalize-Laufzeit, Invalidierung und ausschließlich berechnete Bounds; allgemeiner Containerbaum und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTLAYOUT-0006'; Status = 'Teilweise integriert'; Evidence = 'layout.c: Compact/Standard/Wide-Breakpoints, 3%-Safe-Area und adaptive Brand-/Panel-Anordnung; QEMU-Nachweis in drei echten GOP-Modi, Touch-/Rotationstest fehlt' },
    @{ Pattern = 'NPSPEC-BOOTLAYOUT-0007'; Status = 'Teilweise integriert'; Evidence = 'layout.c: deterministische Ganzzahlskalierung von 1000 bis 2000 sowie Accessibility-Untergrenze; Firmware-DPI ist mangels physischer Displaymetrik sicher auf 96 DPI gesetzt' },
    @{ Pattern = 'NPSPEC-BOOTLAYOUT-0008'; Status = 'Teilweise integriert'; Evidence = 'layout.c: zentrale nova_dlu_to_pixels-Rundung; Panel, Abstände, Radien, Icons und Textskalierung werden daraus abgeleitet; BIOS nutzt eigene kompatible DLU-Tokens' },
    @{ Pattern = 'NPSPEC-BOOTLAYOUT-0009'; Status = 'Teilweise integriert'; Evidence = 'layout.c: validierter Min/Preferred/Max-Constraint-Resolver mit deterministischem Fehlerzähler; vollständige verschachtelte Container-Priorisierung fehlt' },
    @{ Pattern = 'NPSPEC-BOOTLAYOUT-0010'; Status = 'Teilweise integriert'; Evidence = 'layout.c/text.c: Safe-Area, skalierte Textmessung, Ellipsis und Layoutklassen; Hosttests decken 640x480 bis 4K ab, UEFI-QEMU 800x600/1280x720/1920x1080' },
    @{ Pattern = 'NPSPEC-BOOTLAYOUT-'; Status = 'Teilweise integriert'; Evidence = 'layout.c/ui.c: DLU-basierte responsive UEFI-Layoutlaufzeit mit Safe Area und Constraints; BIOS-/UEFI-Parität ist noch offen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-PROGRESS-0001'; Status = 'Teilweise integriert'; Evidence = 'dialog.c/ui.c/motion.c: bestimmter und unbestimmter Progress, 0..1000-Range, Status-/Prozentdarstellung, Theme/High Contrast und QEMU-Abschlussflow; eigenständiges BIOS-Control fehlt' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-SPINNER-0001'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c/main.c: heapfreier Activity Indicator mit validiertem Start/Stop, Phase und Spinner-/Ring-/Dots-/Arc-Templates; die unbestimmte Diagnosephase nutzt produktiv den Spinner ohne numerischen Fortschrittsbalken; Hosttest deckt alle vier Stile ab, QEMU einen stabilen Activity-Frame; kontinuierliche Motion-Timeline und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-CARD-0001'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c/compositor.c: heapfreies Card-Container-Control mit sieben validierten Typen, rekursionssicherer Child-Gruppierung, Theme-Rahmen/Radien und semantischen Information/Warning/Error/Success-Akzenten; die produktive UEFI-Seitenkarte verwendet das Control auf der stabilen Basissurface; zentrale Glass-/Acrylic-Tints und Materialfallbacks sind vorhanden, eine eigene gekachelte Material-Layer sowie BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-TILE-0001'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c/main.c: heapfreies Boot Option Tile mit sieben validierten Typen, Titel/Beschreibung/Status/Aktion, Themefläche, semantischer Typmarkierung und eindeutigem Fokusrahmen; Recovery nutzt produktiv ein responsives 2x3-Grid mit Icons, Status, Maus, Enter/Space und zweidimensionaler Tastaturnavigation; Hosttest und QEMU-Frame/Aktivierung vorhanden; Touch/Controller, Tile-Motion und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-ICONBUTTON-0001'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c/icons.c: spezialisierter heapfreier Icon Button mit validiertem semantischem Icon-Token, Pflicht-Tooltip, Aktion, Accessibility, Hover/Fokus/Pressed/Disabled-Grundzuständen und Themefarben; der Breadcrumb-Root verwendet produktiv den zentrierten Home-Icon-Button mit Text, Pointer, Tab, Enter/Space und QEMU-Root-Reset-Nachweis; SVG-Primärquelle, Touch/Controller, Motion und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-SCROLLVIEW-0001'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c/main.c: heapfreies bidirektionales O(1)-Scrollmodell mit Viewport-/Contentmaßen, X/Y-Clamp und Scroll-Into-View; die Diagnoseansicht nutzt einen echten vierzeiligen vertikalen Viewport, rendert ausschließlich vollständige sichtbare Einträge und unterstützt Pfeile, Page Up/Down, Home/End, Mausrad und gekoppeltes Pointer-Dragging; QEMU-Frame nachgewiesen; Touch/Controller, Smooth Scroll und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-SCROLLBAR-0001'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c: fest an eine ScrollView gebundene horizontale/vertikale Scrollbar mit proportionaler Mindest-Thumbgröße, Track-Sprung, Drag-Zustand, Theme- und Accessibilitydaten; produktiver vertikaler Diagnose-Thumb und QEMU-Screenshot; Auto-Hide/Motion, Touch/Controller und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-PASSWORD-0001'; Status = 'Teilweise integriert'; Evidence = 'dialog.c/ui.c: UTF-8-Secret-Puffer, Maskierung, Längengrenze, codepointweises Löschen und volatile Speicherbereinigung; Cursor/Selection/Paste und Authentifizierungsbackend fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-SWITCH-0001'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c: typisierter Off/On-/Locked-/Busy-Zustand, rundes Track-/Knob-Rendering, Theme/High Contrast, Accessibility und echter Reduced-Motion-Switch in den UEFI-Einstellungen; Motion und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-SLIDER-0001'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c/main.c: produktiver Tooltip-Delay-Slider 250..1500 ms mit 250-ms-Schritten, Clamp, Wertlabel, Links/Rechts/Home/End, Enter/Space, Pointer-Drag, Theme, Accessibility und QEMU-Ablauftest; Touch/Controller, vertikale Variante und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-CHECKBOX-0001'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c/main.c: produktive unabhängige Tooltip-Checkbox mit Checked/Unchecked/Indeterminate-Grundmodell, Enter/Space/Pointer, Theme, Accessibility, exakt einer Änderung je Aktivierung und QEMU-Nachweis; Touch/Controller und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-STATUSBADGE-0001'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c: heapfreies nichtinteraktives StatusBadge mit Information/Success/Warning/Error/Critical/Neutral/Custom, semantischen Themefarben, optionalem Icon, Textfallback, Rundung, Rahmen und Accessibility; alle sechs Recovery-Tiles verwenden Badges produktiv, Hosttests decken Typen/Validierung ab und QEMU belegt Frame sowie Dark/Light/High Contrast. Motion, Live-Region-/Screenreader-Ausgabe und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-CONTEXTMENU-0001'; Status = 'Teilweise integriert'; Evidence = 'ui.c/main.c: exklusives heapfreies Context Menu am Ziel-Control, Safe-Area-Korrektur, Fokusfang, F2/Rechtsklick, Pfeile, Enter, Escape, Outside-Click und sichere Detail-/Optionsaktionen; Untermenüs, Touch und BIOS-Anbindung fehlen; QEMU-Frame und Aktion nachgewiesen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-TEXTFIELD-0001'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c/main.c: produktives UEFI-Hilfesuchfeld mit festem UTF-8-Puffer, Suchfilter, Placeholder, Fokus/Caret, Insert, Backspace, Delete, Links/Rechts/Home/End, Ergebnisaktualisierung, Pointer-Fokus, Accessibility, Themes, Host-Grenztests und vollständigem QEMU-Ablauf; virtuelle Tastatur, Pointer-Textselektion, Caret-Blinken und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-TOOLTIP-0001'; Status = 'Teilweise integriert'; Evidence = 'ui.c/main.c: genau ein zentraler Tooltip mit produktiv konfigurierbarer Aktivierung und 250..1500-ms-Verzögerung, Safe-Area-Positionierung, Theme/High Contrast, kein Fokus-/Input-Capture und sofortigem Ausblenden bei Eingabe, Dialog oder Context Menu; Motion/Touch und BIOS-Anbindung fehlen; QEMU-Frames visuell geprüft' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-BREADCRUMB-0001'; Status = 'Teilweise integriert'; Evidence = 'ui.c/main.c/navigation.c: Unterseiten zeigen Start/Chevron/aktuelle Seite; Start besitzt themebasierte Hover-/Fokuszustände, präzises Pointer-Hit-Testing und Tab/Enter/Space-Aktivierung; die zentrale Navigation setzt den Stack in O(1) auf Root zurück; tiefere Hierarchien, Touch/Controller und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-0003'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c: zentraler heapfreier 32er Style-Manager mit O(1)-ID-Zugriff/-Bindung, aufgelöster Vererbung, Override-Masken, Theme-Neubindung pro Control, semantischen Farbrollen, DLU-Geometrie und Opaque/Glass/Acrylic/Transparent; Dark/Light/High Contrast und Reduced Motion sind in QEMU belegt. Vollständige Typografie-, Effects-/Animationsdeskriptoren, Style-Diagnosezeiten, konsequente Entfernung aller lokalen Renderer-Geometrie sowie identische BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-0004'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c: zentraler heapfreier 64er Template-Manager mit statischem Standardtemplate für jeden Control-Typ, O(1)-Lookup/-Bindung, benannten Partmasken, Pflicht-Part-, Typ- und Rekursionsvalidierung sowie Template-Vererbung; jedes neu erzeugte Control erhält vor Nutzung ein validiertes kompatibles Template, Hosttests und produktiver UEFI-IMG-Frame belegen die Bindung. Ein vollständig renderergetriebener Visual Tree mit Partobjekten, ContentPresenter-Daten, Motion-/Accessibility-Metadaten und identische BIOS-Strukturen fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-0001'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c: heapfreier 128er Pool, Typen, Parent/Child, Lifecycle, Bounds, Dirty-State, Fokus, Hit-Test, exakt-einmal Aktionen, Styles, Accessibility, Werte und typisierte Renderer; Ereignisbubbling und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-0002'; Status = 'Teilweise integriert'; Evidence = 'controls.c: Haupt-, Sichtbarkeits-, Fokus-, Hover-, Pressed-, Selected-, Busy-, Error-, Checked-, Readonly- und Locked-Zustände mit validierten Übergängen und Diagnostik; Zustandsmotion und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c und boot2.asm: gemeinsames typisiertes Controlmodell, datengetriebene Menüeinträge, Fokus, Icons/Text, Hit-Testing und sichere Fallbackdarstellung; spezialisierte Controls werden schrittweise angebunden' },
    @{ Pattern = 'NPSPEC-BOOTTEXT-'; Status = 'Teilweise integriert'; Evidence = 'boot-font-aa.inc; boot2.asm: bm_draw_text, bm_draw_text_wrapped, bm_measure_text' },
    @{ Pattern = 'NPSPEC-BOOTDESIGN-'; Status = 'Teilweise integriert'; Evidence = 'boot-ui-tokens.inc; boot2.asm: Theme-Tokens und Hochkontrastmodus' },
    @{ Pattern = 'NPSPEC-BOOTMANAGER-UI-'; Status = 'Teilweise integriert'; Evidence = 'boot2.asm: vollständiger BIOS-GUI-Pfad; uefi/main.c und bootmenu/ui.c: getesteter GOP-Menü- und Countdown-Grundpfad' },
    @{ Pattern = 'NPSPEC-BOOTDIALOG-0001'; Status = 'Teilweise integriert'; Evidence = 'dialog.c/ui.c: fester Dialogpool und -stack, vollständige Lifecycle-Reihenfolge, Typen, modale Root, Ergebnis und Ressourcenfreiheit; nichtmodale UEFI-Nutzung und BIOS-Parität fehlen' },
    @{ Pattern = 'NPSPEC-BOOTDIALOG-0002'; Status = 'Teilweise integriert'; Evidence = 'dialog.c/ui.c: genau ein aktiver modaler Dialog, Backdrop, Eingabesperre, Safe-Area-Zentrierung, Fokusfang und Escape-Abbruch; Touch fehlt' },
    @{ Pattern = 'NPSPEC-BOOTDIALOG-0003'; Status = 'Teilweise integriert'; Evidence = 'ui.c/compositor.c: abgerundete thematische Dialogfläche, Alpha-Backdrop sowie Glass/Acrylic-Fallback-Infrastruktur; echter Blur-Cache fehlt' },
    @{ Pattern = 'NPSPEC-BOOTDIALOG-0004'; Status = 'Teilweise integriert'; Evidence = 'dialog.c/main.c: Confirmation-Typ, fokussierbare Aktionen, eindeutiges Resultat und sichere Abbruchaktion; BIOS-Anbindung fehlt' },
    @{ Pattern = 'NPSPEC-BOOTDIALOG-0005'; Status = 'Teilweise integriert'; Evidence = 'ui.c/main.c: thematisch markierter Warning-Dialog für blockierte Recovery-, Firmware- und Neustartziele mit verständlichem Text' },
    @{ Pattern = 'NPSPEC-BOOTDIALOG-0006'; Status = 'Teilweise integriert'; Evidence = 'dialog.c/ui.c: Error-Typ, Fehlerfarbtoken und Ergebnisweg; fataler Nova-Fehlerbildschirm existiert separat, Retry-/Detailpfad fehlt' },
    @{ Pattern = 'NPSPEC-BOOTDIALOG-0007'; Status = 'Teilweise integriert'; Evidence = 'dialog.c/ui.c/main.c: sichtbarer bestimmter/unbestimmter Progress, Prozent, Statuswechsel, Abschluss und Close; Werte werden begrenzt, QEMU-Frame nachgewiesen; Task-/Restzeitbackend und BIOS-Parität fehlen' },
    @{ Pattern = 'NPSPEC-BOOTDIALOG-0008'; Status = 'Teilweise integriert'; Evidence = 'dialog.c/ui.c: statischer 128-Byte-Secret-Puffer, UTF-8-Eingabe, Maskierung, codepointweises Backspace, Boundsprüfung und volatile Nullung beim Close; kein Crypto-/TPM-Backend, daher sicher nicht im normalen Flow angefordert' },
    @{ Pattern = 'NPSPEC-BOOTDIALOG-0009'; Status = 'Teilweise integriert'; Evidence = 'dialog.c/ui.c: zyklischer interner Fokus, modale Pointer-Hit-Tests, gespeicherte Vorfokus-ID und Blockade des Hintergrunds; Screenreader/Touch fehlen' },
    @{ Pattern = 'NPSPEC-BOOTDIALOG-0010'; Status = 'Teilweise integriert'; Evidence = 'motion.c/main.c/ui.c: UEFI Enter/Exit mit 180-ms-Fade und 95-auf-100-Prozent-Scale, 150-ms-Reduced-Motion-Fade ohne Scale, finalem Fokus, sicherem Abbruch und stabil synchronisiertem QEMU-Frame; BIOS-Anbindung fehlt' },
    @{ Pattern = 'NPSPEC-BOOTDIALOG-0011'; Status = 'Teilweise integriert'; Evidence = 'dialog.c: genau ein typisiertes Resultat, O(1)-Close, Cancel-Regel und oberster-Dialog-Priorität; asynchroner Callback fehlt' },
    @{ Pattern = 'NPSPEC-BOOTDIALOG-0012'; Status = 'Teilweise integriert'; Evidence = 'dialog.c/main.c: zerstörerische Aktion erfordert nach Fokuswahl eine zweite explizite Bestätigung; QEMU weist Dialog-Arming und echtes ResetSystem-Shutdown nach' },
    @{ Pattern = 'NPSPEC-BOOTNAV-0001'; Status = 'Teilweise integriert'; Evidence = 'navigation.c/page.c/main.c: zentraler heapfreier Zustandscontroller, Navigation Tree, Stack, Fokus, Dialog-/Recovery-Priorität und Transitionen; alternative Eingabegeräte und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTNAV-0002'; Status = 'Teilweise integriert'; Evidence = 'navigation.c: spezifikationsgemäßer statischer 64er O(1)-Stack mit Push/Pop/Replace/Reset, Root-Schutz, vollständigem State und Diagnose; Dialogstack separat, Recovery als typisierter Zweig; BIOS-Anbindung fehlt' },
    @{ Pattern = 'NPSPEC-BOOTNAV-0003'; Status = 'Teilweise integriert'; Evidence = 'page.c/ui.c: feste 16-Page-/64-View-Pools, eindeutige Root-Bäume, strikte Lifecycle, Sichtbarkeit, Layoutboxen, Fokus/Accessibility, iterative Events, Zyklus-/ID-Prüfung und modale Dialog-Pages; QEMU-Aktivierung/-Restore belegt, BIOS-Anbindung fehlt' },
    @{ Pattern = 'NPSPEC-BOOTNAV-0004'; Status = 'Teilweise integriert'; Evidence = 'navigation.c/main.c: Dialog vor Page, O(1)-Back, Root-Schutz und Wiederherstellung von Seite/Auswahl/Fokus/Scroll/Kontext; Breadcrumb-Direktnavigation führt über den zentralen Controller und einen validierten O(1)-Root-Reset; Recovery-Unterstack ist noch nicht separat typisiert' },
    @{ Pattern = 'NPSPEC-BOOTNAV-0005'; Status = 'Teilweise integriert'; Evidence = 'navigation.c/main.c/ui.c: sichtbarer 32-DLU Slide+Fade für Push/Pop, spiegelbildliche Richtung, Cross-Fade für Replace, ruhiger Recovery-Fade, Fokus-Sperre und Reduced-Motion-Fade; QEMU weist transformierte Frames/Richtungen nach, BIOS-Parität fehlt' },
    @{ Pattern = 'NPSPEC-BOOTDIALOG-'; Status = 'Teilweise integriert'; Evidence = 'dialog.c/ui.c: gemeinsame heapfreie UEFI-Dialoglaufzeit; spezialisierte Backends und BIOS-Parität fehlen' },
    @{ Pattern = 'NPSPEC-BOOTNAV-'; Status = 'Teilweise integriert'; Evidence = 'navigation.c/main.c: UEFI-Navigation-Stack mit Zustandswiederherstellung; allgemeiner View-Tree und BIOS-Parität fehlen' },
    @{ Pattern = 'NPSPEC-BOOTRENDER-0001'; Status = 'Teilweise integriert'; Evidence = 'render_queue.c/scene_graph.c/compositor.c/graphics.c/ui.c: plattformneutrale retained UEFI-Renderpipeline über Scene Graph, validierte feste Command Queue, Software-Rasterizer, Offscreen-Compositor und GAL-Present. Der produktive Frame nutzt die Queue für den Hintergrund und traversiert vor jedem Compositing den synchronisierten Control-Szenenbaum; Host und echtes GPT/FAT32-QEMU belegen beide Manager. Vollständige Migration jedes Text-/Icon-/Control-Primitivs auf Commands, PNG/SVG, Pfade/Polygone/Gradienten, Triple Buffer, identischer BIOS-Pfad und gemessene Nanosekundenbudgets fehlen' },
    @{ Pattern = 'NPSPEC-BOOTRENDER-0002'; Status = 'Teilweise integriert'; Evidence = 'render_queue.c/ui.c: heapfreier 1024er Command Buffer pro Frame mit unveränderlicher Kopie, IDs, Type, Layer, Z, Creation Order, Cliphandle, Opacity, Ressourcenhandle, Ziel-Surface und Geometrie. Validierung verwirft ungültige Commands; stabile Sortierung Layer/Z/Erzeugung, horizontale Rechteck-Batches, verschachtelte Clips, fester Reset und Rasterausführung sind hostgetestet. Der echte UEFI-Frame nutzt Clear als Render Command und QEMU meldet RENDER-COMMANDS-READY. Text, Icons und komplexe Controls erzeugen noch teilweise direkte validierte Rasterizeraufrufe; Transform-/Resource-State-Tabellen und alle spezifizierten Commandtypen fehlen' },
    @{ Pattern = 'NPSPEC-BOOTRENDER-0003'; Status = 'Teilweise integriert'; Evidence = 'scene_graph.c/controls.c/ui.c: heapfreier retained 256er Szenenpool mit genau einem unsichtbaren Root, stabiler Parent/FirstChild/NextSibling-Hierarchie, Container/Control/Dialog/Graphic/Text/Overlay/Cursor-Typen, Bounds, 16.16-Matrix, Opacity, Visibility/Hidden/Collapsed, Enabled, Layer/Z, Ressourcenhandle und vier Dirtyklassen. Attach/Detach/Destroy verhindern Zyklen, Mehrfacheltern und Elternabbau vor Kindern; lineare Traversierung akkumuliert Transformation, Opacity, Sichtbarkeit und Bounds. Jedes produktive Control wird automatisch registriert und vor jedem UEFI-Frame synchronisiert/traversiert; Host und QEMU belegen den Pfad. Dialog/Page/View-Objekte außerhalb des Control-Pools, Command-Erzeugung ausschließlich aus Traversal, Rotation/Skalierungs-Bounds, Memory-Manager-Allokation und BIOS-Parität fehlen' },
    @{ Pattern = 'NPSPEC-BOOTRENDER-0004'; Status = 'Teilweise integriert'; Evidence = 'surface_manager.c/layer_manager.c/ui.c/compositor.c: zentraler fester Manager mit 256 generationensicheren Surfaces und 512 generationensicheren Layern, 32er Tiefengrenze, overflow-fester 64-Byte-Pitch-/Größenrechnung, getrennten Persistent/Scene/Effect/Frame/Emergency-Pools, harten Budgets, Recycling, Referenzen, exklusivem Lock/Unlock samt Damage, Frame-Reset und vorreservierter Emergency-Surface. Layer decken alle Standardklassen, stabile Klasse/Z/Creation/ID-Sortierung, Hierarchie/Zyklenschutz, Worldtransform/Opacity/Clip-Vererbung, AUTO/REQUIRED/CACHED/TRANSIENT-Isolation, Surface-Bindung, Parent-Damage und Mutationssperren in Traversal/Compositing/Present ab. Der echte UEFI-Pfad importiert beide Compositorflächen, verwaltet Background/Content/Control/Dialog/Overlay/Cursor/Emergency und QEMU meldet beide Manager bereit. Vollständige Mutation Queue, Masken, Cache-Eviction, Triple Buffer, partielle Present-Regionen, automatische Quality-Degradationskette und gemeinsame BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTRENDER-0005'; Status = 'Teilweise integriert'; Evidence = 'framebuffer_backend.c/graphics.c/compositor.c und uefi/graphics.c: einheitliches initialisierbares Backend für VBE/GOP/Test/Virtual mit validierter Adresse, Width/Height, bytegenauem Pitch, BPP, Format, Mappinggröße und Capability-Auskunft. Bounds-geprüfte Pixel-Read/Write-, Horizontal-/Vertikallinien-, Rechteck- und kanonische Blockkopier-API berücksichtigt Pitch und RGBA/BGRA/RGB/BGR/RGB565/Bitmask-Konvertierung. Atomare Begin/Damage/Present-Frames mergen bis 32 Regionen und kopieren ausschließlich valide Dirty Regions; der Compositor präsentiert nur noch über das Backend, nicht direkt über GOP/GAL. Diagnose zählt Frames, Presents, Full/Partial, Bytes, Zugriffe und Fehler. Hosttests beweisen fremde Pixel bei Partial Present unverändert sowie Bounds/Pitch; echtes GPT/FAT32-QEMU meldet FRAMEBUFFER-BACKEND-READY und elf GAL-Presents. Der C-Backendvertrag ist im platzkritischen BIOS-Assembler noch nicht angebunden; expliziter Single-Buffer-Modus, Cache-Flush/MMIO-Barrieren, Remote/Virtual-Implementierung und Bare-Metal-Tests fehlen' },
    @{ Pattern = 'NPSPEC-BOOTRENDER-0006'; Status = 'Teilweise integriert'; Evidence = 'gop_backend.c sowie uefi/graphics.c: getrennte firmwareunabhängig hosttestbare GOP-Policy und dünner UEFI-Adapter. LocateProtocol, bis zu 64 QueryMode-Ergebnisse, Current/Preferred/Fallback-Auswahl, SetMode und vollständige Active-Mode-Neuvalidierung sind deterministisch. Width/Height, PixelsPerScanLine, RGB/BGR/BitMask, disjunkte Farbmasks, FrameBufferBase, FrameBufferSize, Pitch und overflow-feste Mindestgröße werden vor dem gemeinsamen Graphics-/Framebuffer-Backend geprüft; BLT-only wird kontrolliert abgewiesen. Versionierter Descriptor liefert Adresse, Größe, Auflösung, Pitch, BPP, Format, Masks und Modezählung; Diagnose erfasst Kandidaten, Ablehnungen, Auswahlart, Modewechsel und Queries. Hosttests decken Current/Preferred/Fallback/fehlend/BLT-only/Descriptor/Shutdown ab; QEMU belegt normales GPT/FAT32 sowie explizit 800x600, 1280x720 und 1920x1080 mit GOP-MODES-VALIDATED und echten Presents. UEFI-NBHP/BIB-Kernelhandoff des Descriptors, GOP-not-found-Injektion, BitMask-QEMU-Modus und reale Firmware-/Bare-Metal-Matrix fehlen' },
    @{ Pattern = 'NPSPEC-BOOTRENDER-0007'; Status = 'Teilweise integriert'; Evidence = 'bios/boot2.asm: VBE-2.0-ControllerInfo wird mit VBE2-Signatur angefordert, VESA-Signatur und Version werden geprüft und die untrusted Modusliste wird auf 256 Einträge begrenzt inventarisiert. Die Auswahl folgt deterministisch 1920x1080, 1600x900, 1366x768, 1280x720, 1024x768, 800x600 und danach kompatiblen Modi. Jeder Kandidat sowie der gewählte Modus vor und nach SetMode werden auf supported/graphics/LFB, 32 BPP Direct Color, PhysBasePtr, Width/Height, Pitch, Pitch*Height, Adressüberlauf und exakte BGRX-Masks geprüft. Das BIB erhält Adresse, Pitch, Auflösung, BPP und Format; Fehler löschen Flag und Graphics-Payload und booten im Textmodus weiter. QEMU belegt BACKEND-READY plus Modusrang mit std VGA sowie TEXT-FALLBACK und NOVA_KERNEL_READY mit -vga none. Der gemeinsame C-Framebuffer-Presentvertrag ist noch nicht an den BIOS-Assembler gebunden; explizite Farbmasks und Framebuffergröße passen nicht in den aktuellen BIB-v1.2-Graphics-TLV, RGB888/RGB565 widersprechen der 32-Bit-Voraussetzung und sind nicht aktiviert; Invalid-Mode-Firmwareinjektion und Bare-Metal-Tests fehlen' },
    @{ Pattern = 'NPSPEC-BOOTRENDER-0008'; Status = 'Teilweise integriert'; Evidence = 'present_scheduler.c/compositor.c: zentraler heapfreier Present Scheduler liegt produktiv zwischen Compositor und Framebuffer Backend. Double Buffer ist Standard; ein optionaler beim Start bereitgestellter dritter Buffer durchläuft Rendering/Ready/Presenting/Displayed. Der globale Lock verhindert paralleles Rendern, 64 Dirty Regions werden validiert und überlappend vereinigt, über 60 Prozent Fläche oder Backendgrenzen erzwingen Full Present. First/Forced/Partial Present, Frame-/Render-/Presentzeiten, VSync-/Pageflip-Capabilities und umfangreiche Diagnose sind typisiert. Ein Presentfehler wird genau einmal als Full Present wiederholt und eskaliert anschließend über den Recovery Manager in Safe Mode, ohne Zustand oder Lock festzuhalten. Hosttests belegen Double/Triple, Zustände, Lock, Merge, Full/Partial, Timing und Recovery; OVMF/QEMU belegt PRESENT-SCHEDULER-READY sowie 15 erfolgreiche Frames. BIOS verwendet weiterhin seinen direkten LFB-Pfad; echtes VSync/Page-Flipping, produktiv aktivierter Triple Buffer, Hardwarezeitmessung und Tearing-/Bare-Metal-Nachweise fehlen' },
    @{ Pattern = 'NPSPEC-BOOTRENDER-0009'; Status = 'Teilweise integriert'; Evidence = 'dirty_manager.c/compositor.c/present_scheduler.c: zentraler heapfreier Dirty Manager mit konfigurierbarer Kapazität bis 64 und konfigurierbarem Flächenschwellwert. Er verwirft leere/außerhalb liegende Rechtecke, clippt overflow-fest an den Bildschirm, unterdrückt Duplikate, vereinigt transitiv alle Überlappungen und eskaliert Kapazität oder mindestens 50 Prozent Fläche zu typisiertem Full Damage. Blur-, Shadow- und Alpha-Extents erweitern Regionen overflow-fest; Layer-Schnittprüfung und Diagnosen für Add/Merge/Clip/Expansion/Flächen/Full-Gründe sind vorhanden. Der Compositor speist ausschließlich diesen Manager, dessen Damage Set unverändert an den Present Scheduler geht. Hosttests decken Einzel/Mehrfach/Overlap/Duplikat/Clipping/Threshold/Capacity/Effect-Expansion/Overflow ab; QEMU meldet DIRTY-MANAGER-READY und präsentiert weiterhin elf Frames aus dem GPT/FAT32-Image. Controls und Animationen zeichnen produktiv noch überwiegend vollständige Layer neu; Maus-alt/neu ist nicht explizit an den Manager angebunden, BIOS-Parität sowie Performance-/Bare-Metal-Messungen fehlen' },
    @{ Pattern = 'NPSPEC-BOOTRENDER-0010'; Status = 'Teilweise integriert'; Evidence = 'clip_mask.c/render_queue.c: zentraler heapfreier Clip-/Mask-Manager mit exakt einem Rootclip pro Frame, 32er verschachteltem Stack, 64 unveränderlichen effektiven Scopes, Intersection, Inside/Partial/Outside-Frühklassifikation und Overflow-/Underflowschutz. 64 generationensichere Masken unterstützen Rectangle, 1-Bit-Bitmap, 8-Bit-Alpha, callbackbasierte Vector und Rounded Rectangle; Maskscopes kombinieren beliebig bis Tiefe 32 per Alpha-Multiplikation. Pointer/Stride/Size/Radius/Bounds werden geprüft, aktive/rekursive Masken abgewiesen und ein 256er statischer Coverage-Cache diagnostiziert Hits/Misses. Render Commands erfassen Clip- und Maskscope beim Submit; Clear/Rect/Line/Circle verwerfen unsichtbare Bounds früh, clippen jeden Schreibzugriff und skalieren Quellalpha vor späterem Compositing. Hosttests decken Root/Dialog/Scroll/Nesting, Full/Partial/Outside, alle fünf Masktypen, Kombination, Cache, Recursion, Lifecycle und einen tatsächlich maskierten Rasterpixel ab; QEMU meldet CLIP-MASK-READY und bootet das GPT/FAT32-Image. Direkte ältere Text/Icon/Control-Rasterizer sind noch nicht vollständig auf Commands migriert; Ellipse/Polygon/Bezier, vollständige produktive Dialog-/Scrollmaskbindung, BIOS-Parität und SIMD fehlen. Die zwei contentReference-Platzhalter in der Draft-NPSPEC sind redaktionell ungültig, ändern aber keine technisch auslegbare Anforderung' },
    @{ Pattern = 'NPSPEC-BOOTRENDER-0011'; Status = 'Teilweise integriert'; Evidence = 'transform2d.c/scene_graph.c/layer_manager.c/render_queue.c: gemeinsame affine 3x2-API mit Float-Vertrag und deterministischer 16.16-Hotpathdarstellung. Identity, Translation, Rotation im Bogenmaß, Scale, negative Mirror-Skalen, X/Y-Shear, Pivot, Parent*Child, Inverse, Point und Four-Corner-Bounds sind validiert; NaN/Inf, Komponentenlimit, singuläre/overflowende Fixed-Matrizen und Stackfehler werden abgewiesen. Eigene Sin/Cos-Reduktion behandelt Kardinalwinkel ohne libm. Der 32er Transformstack bildet Worldmatrizen; Scene Graph und Layer Manager teilen dieselbe geprüfte Multiplikation und akzeptieren nun 90-Grad-Matrizen. Commands erfassen den aktuellen Transform unveränderlich, transformieren Bounds vor Clip/Mask und rasterisieren Rect/Circle invers sowie Lines über transformierte Endpunkte. Hosttests belegen S->R->T, Pivot, Mirror, Shear, Inverse/Roundtrip, Float->Fixed, Stack, 90-Grad-World-Bounds und ein tatsächlich skaliert/verschobenes Rasterobjekt; QEMU meldet TRANSFORM2D-READY. Alte direkte Text/Icon/Image/Control-Pfade, automatische Old/New-Damage-Anbindung, produktive Rotation/Scale-Animationen, BIOS-Parität, SIMD und echte Mikrosekundenmessungen fehlen. Der contentReference-Platzhalter in der Draft-NPSPEC ist redaktionell ungültig, aber technisch nicht blockierend' },
    @{ Pattern = 'NPSPEC-BOOTRENDER-0012'; Status = 'Blockiert'; Evidence = 'Die Datei NPSPEC-BOOTRENDER-0012_Alpha_Compositing.md ist inhaltlich bytegleich mit NPSPEC-BOOTRENDER-0011_2D_Transformations.md, trägt intern Dokument-ID NPSPEC-BOOTRENDER-0011 und den Titel 2D Transformations und enthält keine Alpha-Compositing-Anforderung. Damit fehlen insbesondere normatives Farbmodell, Straight-/Premultiplied-Alpha-Festlegung, Operatoren, Rundungsreihenfolge, API und Akzeptanztests. Vorhandenes Legacy-Blending wird deshalb nicht als Konformitätsnachweis für 0012 gewertet' },
    @{ Pattern = 'NPSPEC-BOOTRENDER-0014'; Status = 'Teilweise integriert'; Evidence = 'rounded_geometry.c/controls.c/ui.c/render_queue.c: gemeinsame heapfreie mathematische Rounded-Geometry-API mit uniformen und vier individuellen Radien, automatischem min(width,height)/2-Clamp, 16.16-DLU-Skalierung, Parameter-Lerp, formgenauem Hit Testing, Disabled/2x2/4x4-AA, Inside/Centered/Outside-Rahmen und Diagnosen. Controls und Panels verwenden produktiv denselben AA-Renderer statt separater kantiger Scanline-Helfer. Ein eigener unveränderlicher Render Command rastert Rounded Rectangles invers unter Translation/Rotation/Scale/Mirror und integriert Clip- und Maskscopes. Hosttests decken Radius 0/Maximum/Einzelradien/AA/Scale/Animation/Border/Hit Test/transformiertes Clipping ab; GPT/FAT32 unter OVMF/QEMU meldet ROUNDED-GEOMETRY-READY. Die referenzierte NPSPEC-BOOTRENDER-0013 Gradients fehlt als Datei und 0012 ist falsch befüllt; daher sind Gradient-, Blur- und Shadow-Konturintegration sowie behauptete BIOS-Pixelparität nicht abschließbar' },
    @{ Pattern = 'NPSPEC-BOOTRENDER-0015'; Status = 'Teilweise integriert'; Evidence = 'effects.c/rounded_geometry.c/ui.c: gemeinsames heapfreies Achtfach-Effektdatenmodell für Drop/Inner/Ambient/Contact Shadow sowie Outer/Inner/Focus/Accent Glow mit RGBA, Radius, Opacity, negativen/positiven Offsets, stabiler Listenreihenfolge, Clear und Parameter-/Farb-Lerp. Konturen werden direkt aus vier individuellen Rounded-Radien abgeleitet; Low/Standard/High begrenzen den Arbeitsradius deterministisch. Shadow- und Glowphasen sind getrennt, Maskcoverage und harter Clip werden vor jedem boundsgeprüften Pixel angewandt, Damage wird gemeldet, Diagnosen zählen Typen/Pixel/Radius/Qualität. Dialoge verwenden produktiv Ambient plus versetzten Drop Shadow; High Contrast reduziert Effekte. Hosttests decken alle acht Typen, Kapazität, ungültige Werte, Animation, Qualität und echten Alpha-Maskscope plus Clip ab; GPT/FAT32/OVMF meldet SHADOW-GLOW-READY. Ein echter separabler Blur-Kernel, Effektcache, Renderzeitmessung, produktive Focus/Hover-Motion, vollständige Render-Object-Anbindung und BIOS-Pixelparität fehlen; 0012 Alpha ist falsch befüllt und 0013 Gradients fehlt' },
    @{ Pattern = 'NPSPEC-BOOTRENDER-0016'; Status = 'Teilweise integriert'; Evidence = 'background_blur.c/ui.c: heapfreier Background-Blur mit getrenntem fertigem Hintergrund-/Ziel-Surface-Vertrag, 512x512-Ergebnis-Cache und 65-Zeilen-Ring statt Render-Hotpath-Allokation, Region-/Surface-/Radiusvalidierung, Box/Gaussian/Dual-Pass-Gaussian, Low/Standard/High und getrennten Horizontal-/Vertikalpässen. In-place-Aufrufe werden kontrolliert abgewiesen. Rounded-4x4-AA und kombinierte Alpha-Masken greifen nach dem Kernel; Damage, überlappungssensitive Invalidierung, Rekursionsschutz, Shutdown und speicherbudgetbedingte Low-Degradation sind typisiert. Hosttests belegen Impulsverteilung, gerundete Kante, Cache Hit/Miss, fremde/überlappende Dirty Regions, Speichermangel und echten Alpha-Maskscope. Nach Reduktion des PE-Images von 40,8 auf 33,7 MiB bootet das reale GPT/FAT32-Image unter OVMF wieder und meldet BACKGROUND-BLUR-READY. Der verlängerte echte Dialogtest belegt Blur-Miss, folgenden Cache-Hit, stabilen Screenshot, Escape, Exit-Motion und Seitenwiederherstellung. Größere Ergebniscaches/Tiling, SIMD, Renderzeitmessung, automatische Layer-Dirty-Generation, BIOS-Pixelparität sowie der fehlende 0012-Alpha-Vertrag bleiben offen' },
    @{ Pattern = 'NPSPEC-BOOTRENDER-0017'; Status = 'Teilweise integriert'; Evidence = 'image_renderer.c/branding.c/controls.c: gemeinsamer vorab dekodierender Image Loader und heapfreier Render-Hotpath mit festem 512-KiB-Pixelcache und 240-KiB-Decodebereich. RAW RGBA/BGRA/RGB/RGB565, internes BMP24/32 und PNG 8-Bit Truecolor/RGBA/Indexed einschließlich PLTE/tRNS, CRC, Adler-32, Stored/Fixed/Dynamic Deflate und allen fünf PNG-Filtern werden validiert und in premultiplied RGBA konvertiert; APNG und Interlacing werden definiert abgewiesen. Ressourcen-ID-Cache/Referenzen, Größen-/Stride-/Overflow-/Budgetgrenzen, Nearest/Bilinear, Fit/Fill/Stretch/Original, affine Transformation, Spiegelung, Clip, Mask, Opacity/Tint, Layer-Surface und Damage sind integriert. Das produktive Nova-Logo läuft über diesen Renderer; der Identitätspfad vermeidet Hotpath-Divisionen pro Pixel. Hosttests belegen RAW, Premultiplikation, Cache, Bilinear/Nearest, Mirror/Transform/Clip, BMP, RGBA-/RGB-/Indexed-PNG, Stored/komprimiertes Deflate, CRC- und Interlace-Fehler. OVMF/QEMU meldet IMAGE-RENDERER-READY und durchläuft Menü sowie Dialog/Blur/Escape/Restore. Offen bleiben BAP-Dateiladen wegen BOOTRESOURCE-0002/0003, BIOS-Pixelparität, SIMD, belastbare Decode-/Renderzeitmessung, größere Bild-/Speichermangel-Fuzztests und der normative Alpha-Compositing-Vertrag aus der falsch befüllten 0012' },
    @{ Pattern = 'NPSPEC-BOOTRENDER-0018'; Status = 'Teilweise integriert'; Evidence = 'render_quality.c plus diagnostics/ui/controls/branding/effects: zentraler heapfreier Quality Manager mit Ultra, High, Standard, Performance und Safe sowie validierten unveränderlichen Parametertabellen für Blur, Shadow/Glow, AA, Imagefilter, Animation, Transparenz, Dithering, Effektanzahl, Speicherbudget und Compositor-Fallback. Konfiguration schlägt Hardware-Autoauswahl; Safe Mode und Grafikfehler eskalieren kontrolliert. Wechsel invalidieren Blur-Cache, setzen alle angebundenen Subsysteme atomar, erzwingen Full Damage und werden diagnostiziert. Dauerhafte Frameüberschreitung degradiert erst nach drei Messungen, Speichermangel sofort; Entscheidungen liegen außerhalb des Render-Hotpaths. Dialogblur/-shadow/-transparenz, Rounded-AA, Logo-Skalierung, Motion, Effekt-Density und Compositor konsumieren das aktive Profil produktiv. Hosttests decken alle fünf Profile, Invalidwerte, Safe, Hardwarewahl, Hysterese, Speicherdegradation, Cache/Full-Redraw ab. GPT/FAT32/OVMF meldet RENDER-QUALITY-READY und besteht Menü sowie Dialog/Blur/Escape/Restore. Offen bleiben persistentes Konfigurations-Backend, echte GPU-/Firmware-Leistungsinventarisierung, produktives Dithering und Renderauflösung, profilabhängig neu dimensionierte bereits reservierte Pools, Recovery nach Leistungsverbesserung, BIOS-Parität und Bare-Metal-Messungen' },
    @{ Pattern = 'NPSPEC-BOOTRENDER-0019'; Status = 'Teilweise integriert'; Evidence = 'software_renderer.c/ui.c/main.c plus render_queue/clip_mask: gemeinsame heapfreie CPU-Renderer-Lifecycle-API mit Initialize/Shutdown/Begin/Scene-Render/Present/Complete/Reset/Availability und Scalar-SIMD-Referenzpfad. Die produktive UEFI-GUI läuft über Render Commands, Scene Graph, Software-Rasterizer, Compositor und Framebuffer; jeder Frame wird typisiert begonnen und abgeschlossen. Render-/Presentfehler eskalieren deterministisch über Command-/Clip-Abort, Cache Clear und Full Repaint, danach Safe Quality und bei drittem Folgefehler funktionalen UEFI-Textfallback. Speichermangel schaltet Safe, leert Blur und erzwingt Full Damage; doppelter Shutdown, fehlender Framebuffer und ungültige Szenen werden kontrolliert behandelt. Diagnosen erfassen Zustand, Renderer, Frames, Presents, Pixel, Draw Calls, Dirty Regions, Cache, Speicher, Resets, Safe und Text. Hosttests belegen Scene-Traversierung, Erfolg, Memory, vollständige Eskalation und fehlenden Framebuffer. OVMF/QEMU meldet SOFTWARE-RENDERER-READY, bootet Menü/Dialog ohne GPU-API und ein eigener F11-Diagnosetest belegt RESET und RECOVERED mit weiter gezeichneter GUI. BIOS besitzt weiterhin seinen eigenen validierten VBE-LFB-Softwarepfad und Textfallback, nutzt aber noch nicht dieselbe C-Pipeline; Gradienten fehlen mangels 0013-Datei, 0012 Alpha ist falsch befüllt. SIMD-Laufzeitwahl, Reinitialisierung aller persistenten Surface-Pools, identische BIOS-Pixelresultate und Bare-Metal-Fehlerinjektion bleiben offen' },
    @{ Pattern = 'NPSPEC-BOOTRENDER-'; Status = 'Teilweise integriert'; Evidence = 'UEFI: retained Scene Graph, fester Render-Command-Buffer, Rasterizer, Offscreen-Compositor, Dirty Regions und GAL-Present; spezialisierte Detailanforderungen sowie vollständige BIOS-Parität werden je Dokument weiter abgearbeitet' },
    @{ Pattern = 'NPSPEC-BOOTCOMPOSITOR-'; Status = 'Teilweise integriert'; Evidence = 'compositor.c: feste Surface-/Layer-Pools, stabile Z-Sortierung, Alpha, Overlay/Modal, Damage Merge, Glass/Acrylic und Safe-Fallback; BIOS-Anbindung und echter Blur fehlen' },
    @{ Pattern = 'NPSPEC-BOOTMOTION-0007'; Status = 'Teilweise integriert'; Evidence = 'motion.c/navigation.c: zentrale Property-Timeline erzeugt gruppierte Offset-/Opacity-Transitionen, sperrt Fokus, unterstützt Cancel und Reduced Motion; Materialgruppen und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTMOTION-0009'; Status = 'Teilweise integriert'; Evidence = 'main.c/ui.c/navigation.c: alle UEFI-Menüwechsel laufen über Exit/atomaren Stackwechsel/Enter; Push links, Pop rechts, Recovery/Replace Fade, deterministische Software-Keyframes und QEMU-Transformnachweis; BIOS-Anbindung fehlt' },
    @{ Pattern = 'NPSPEC-BOOTMOTION-'; Status = 'Teilweise integriert'; Evidence = 'motion.c: globale Millisekunden-Timeline, O(n)-Pool-Scheduler, Properties, Easing/Spring-Fallback, Transition/Dialog/Navigation/Fokus/Progress, Unterbrechung, Reduced Motion und Budget-Degradation; BIOS-Anbindung fehlt' },
    @{ Pattern = 'NPSPEC-BOOTRESOURCE-'; Status = 'Teilweise integriert'; Evidence = 'Statisch validierte Font-, Icon- und Logo-Ressourcen; BAP-Loader fehlt' },
    @{ Pattern = 'NPSPEC-BOOTDIAG-'; Status = 'Teilweise integriert'; Evidence = 'diagnostics.c: strukturierter 256er Ringpuffer, Schweregrade, Rendering-/Input-/Motion-/Resource-Snapshots, Frame-/Speicher-/Qualitätsmetriken und QEMU-Initialisierungsnachweis; persistenter Export fehlt' },
    @{ Pattern = 'NPSPEC-BOOTTEST-'; Status = 'Teilweise integriert'; Evidence = 'Makefile: BIOS-, Maus-, Theme-, UI-, Recovery-, Plattform-, UEFI-Autostart-, UEFI-Eventqueue/Navigation-, ELF- und Fehlertests' },
    @{ Pattern = 'NPSPEC-BOOTPERF-'; Status = 'Teilweise integriert'; Evidence = 'diagnostics.c: 16,67/33,33-ms-Framebudget, Teilzeiten, 32-MiB-Low-End-Speicherbudget, Peak/Cache/Pool, adaptive und feste Qualitätsprofile sowie Safe-Fallback; hardwarebasierte GPU/High-End-Erkennung fehlt' }
)

$rows = foreach ($file in $files) {
    $raw = Get-Content -LiteralPath $file.FullName -Raw -Encoding UTF8
    $relative = $file.FullName.Substring($root.Length + 1).Replace('\', '/')
    $id = [regex]::Match($file.BaseName, 'NPSPEC-[A-Z0-9-]+').Value.TrimEnd('-')
    if ([string]::IsNullOrWhiteSpace($id)) { continue }
    if ([string]::IsNullOrWhiteSpace($raw)) {
        [pscustomobject]@{ Id=$id; File=$relative; Status='Blockiert'; Evidence='Spezifikationsdatei ist leer' }
        continue
    }
    $rule = $evidenceRules | Where-Object { $id -like "$($_.Pattern)*" } | Select-Object -First 1
    if ($rule) {
        [pscustomobject]@{ Id=$id; File=$relative; Status=$rule.Status; Evidence=$rule.Evidence }
    } else {
        [pscustomobject]@{ Id=$id; File=$relative; Status='Prüfung offen'; Evidence='Noch keine explizite Implementierungszuordnung' }
    }
}

$lines = @(
    '# NovaOS Bootmanager NPSPEC-Abdeckung',
    '',
    "Erzeugt: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')",
    '',
    "Dokumente: $($rows.Count)",
    '',
    '| NPSPEC | Status | Implementierungsnachweis | Datei |',
    '|---|---|---|---|'
)
foreach ($row in $rows) {
    $lines += "| $($row.Id) | $($row.Status) | $($row.Evidence) | $($row.File) |"
}

$target = [IO.Path]::GetFullPath((Join-Path (Get-Location) $OutputFile))
$directory = Split-Path -Parent $target
if (-not (Test-Path -LiteralPath $directory)) { New-Item -ItemType Directory -Path $directory | Out-Null }
[IO.File]::WriteAllLines($target, $lines, [Text.UTF8Encoding]::new($false))

$rows | Group-Object Status | Sort-Object Name | ForEach-Object {
    Write-Host ("{0}: {1}" -f $_.Name, $_.Count)
}
Write-Host "Abdeckungsmatrix: $target"
