param(
    [string]$DocsRoot = 'docs/NPSPEC/Boot',
    [string]$OutputFile = 'build/bootmanager-npspec-coverage.md'
)

$ErrorActionPreference = 'Stop'
$root = (Resolve-Path -LiteralPath $DocsRoot).Path
$files = Get-ChildItem -LiteralPath $root -Recurse -File -Filter '*.md' | Sort-Object FullName

$evidenceRules = @(
    @{ Pattern = 'NPSPEC-BOOTCONTROL-LISTITEM-0001'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c/main.c: heapfreies typisiertes ListItem mit Titel, Subtitle, Status, stabiler ID/Reihenfolge, Normal/Hover/Focus/Selected/Disabled/Pressed/Error, Theme-Rundung, eindeutiger Auswahlmarkierung, Icon-/Label-Komposition und Accessibility; Haupt-, Settings-, Diagnose-, Power-, Firmware- und Hilfelisten nutzen es produktiv mit Maus, Tastatur, Space und Kontextmenü; Touch/Doppelklick, Item-Motion und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-LIST-0001'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c/main.c: feste indexierbare 64er Item-Collection im 128er Control-Pool mit stabiler Reihenfolge, Add/Remove, None/Single/Multi, O(1)-Direktauswahl, Fokus, sichtbarem Virtualisierungsfenster und ScrollView-Kopplung; produktive Bootmanager-Listen unterstützen Pfeile, Home/End, Page Up/Down, Enter/Space, Maus und QEMU-Nachweis; Touch/Controller, sehr große Providerlisten, Insert/Remove-Motion und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-LABEL-0001'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c/text.c: heapfreies Label-Control mit neun Typen, neun horizontal/vertikal kombinierten Ausrichtungen, Ein-/Mehrzeile, Wrap/Ellipsis, dynamischem UTF-8-Text, Theme-/Statusfarben und DPI-Skalierung; Wortmarke und Statuszeile nutzen es produktiv, Host- und QEMU-Nachweise vorhanden; relationale Beschriftung, Motion und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-ICON-0001'; Status = 'Teilweise integriert'; Evidence = 'controls.c/icons.c/ui.c: heapfreies semantisches Icon-Control mit validierten zentralen Token-Ressourcen, proportionaler DLU-Skalierung, Theme-/Disabled-/Statusfarben und dekorativ/semantischer Accessibility; alle sechs sichtbaren Menü-/Tile-Icons nutzen es produktiv, Host- und QEMU-Nachweis vorhanden; allgemeiner SVG-Primärpfad, Motion und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-IMAGE-0001'; Status = 'Teilweise integriert'; Evidence = 'controls.c/branding.c/resources.c/ui.c: heapfreies Image-Control mit Original/Stretch/Fit/Fill/Center, Clipping, Alpha-Coverage, Tint und zentral wiederverwendeter validierter NovaOS-Logo-Ressource; das Branding nutzt produktiv Fit und Theme-Tint, Host- und QEMU-Nachweis vorhanden; weitere PNG/BMP/QOI/SVG-Decoder bleiben durch fehlendes BAP-/Index-Wire-Format blockiert, Motion und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-SEPARATOR-0001'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c: nicht-interaktives heapfreies Separator-Control mit horizontaler/vertikaler Ausrichtung, optionalem zentriertem Titel, Theme-Linie und dekorativer Accessibility; die Settings-Gruppen werden produktiv horizontal getrennt, Host- und QEMU-Framebuffer-Nachweis vorhanden; Icon-Variante, Theme-Fade und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-BUTTON-0001'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c/dialog.c: heapfreies Button-Control mit sieben validierten Typen, Text/Icon, Aktion, Pressed-/Toggle-/Busy-Schutz, exakt-einmal-Auslösung, Theme, Rundung, Fokus und Accessibility; Dialogaktionen verwenden produktiv Primary/Secondary/Destructive Buttons, Host- und QEMU-Dialogtests sind grün; Touch/Controller, vollständige Motion und gemeinsame BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-MENUBUTTON-0001'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c/main.c: heapfreier Menu Button mit validierter 1:1-Menübindung, Collapsed/Expanded, Pfeilindikator, Safe-Area-Overlay und Fokus-Rückgabe; die Theme-Auswahl verwendet ihn produktiv mit Maus, Enter/Space, Pfeilen, Home/End, Escape/Links und drei Theme-Aktionen; Hosttests sowie QEMU-Marker/Framebuffer-Nachweis vorhanden; Touch/Controller, Arrow-Motion, Untermenüs und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTRESOURCE-0002'; Status = 'Blockiert'; Evidence = 'BAP beschreibt Inhalte semantisch, definiert aber kein normatives Wire-Format: Magic-Wert, Headergröße, Feldoffsets/Endianness und Gesamtprüfsummenverfahren fehlen' },
    @{ Pattern = 'NPSPEC-BOOTRESOURCE-0003'; Status = 'Blockiert'; Evidence = 'Resource-Index-API ist beschrieben, aber binäre Packung, Hash-/ID-Ableitung, Tabellenheader und Kollisionsverfahren sind nicht normativ festgelegt' },
    @{ Pattern = 'NPSPEC-BOOTRESOURCE-0001'; Status = 'Teilweise integriert'; Evidence = 'resources.c: zentrale URI/ID-Registry, fester Pool, CRC32-Prüfung, Lazy Load, Cache und Referenzzählung; Font, Icons und gemeinsames NovaOS-Logo sind registriert; BAP-/Dateisystemloader bleibt blockiert' },
    @{ Pattern = 'NPSPEC-BOOTTEXT-0003'; Status = 'Teilweise integriert'; Evidence = 'unicode.c/text.c: validierender UTF-8-Decoder bis U+10FFFF, Overlong-/Surrogat-Abweisung, U+FFFD-Missing-Glyph, UTF-8-Umlaute, Block-/Fehlertests und Diagnose; internationale Glyphatlanten fehlen' },
    @{ Pattern = 'NPSPEC-BOOTDESIGN-0009'; Status = 'Teilweise integriert'; Evidence = 'icons.c/ui.c: alle 15 semantischen O(1)-Tokens besitzen zentral registrierte, geprüfte 2-Bit-AA-Ressourcen; Unterseiten verwenden eigene Tokenzuordnungen, DLU-Skalierung, Theme-Tint, Cache-Diagnose und ausschließlich einen Fallback für ungültige externe Tokens; allgemeiner SVG-Renderer und BIOS-Parität der neun erweiterten Symbole fehlen' },
    @{ Pattern = 'NPSPEC-BOOTDESIGN-0002'; Status = 'Teilweise integriert'; Evidence = 'theme.c: validierte statische O(1)-Token-Tabellen für Farben, Abstände, Radien, Transparenz, Material und Motion-Overrides; Typography-/Shadow-Registry noch nicht vollständig' },
    @{ Pattern = 'NPSPEC-BOOTDESIGN-0003'; Status = 'Teilweise integriert'; Evidence = 'theme.c/ui.c: sämtliche UEFI-Farben über semantische Rollen, deterministischer Kontrasttest, Focus/Selected/Disabled/Statusfarben und Accessibility-Overrides; BIOS nutzt weiterhin eigene äquivalente Tokenquelle' },
    @{ Pattern = 'NPSPEC-BOOTDESIGN-0012'; Status = 'Teilweise integriert'; Evidence = 'UEFI und BIOS: Dark Theme; UEFI aus zentral validierter Token-Tabelle mit dynamischen Controls, Icons, Branding, Fokus und Materialien; allgemeine externe Theme-Resource fehlt' },
    @{ Pattern = 'NPSPEC-BOOTDESIGN-0013'; Status = 'Teilweise integriert'; Evidence = 'theme.c: vollständiger statischer Light-Token-Satz; QEMU-Wechsel und visueller Framebuffer-Nachweis; BIOS-Light-Theme fehlt' },
    @{ Pattern = 'NPSPEC-BOOTDESIGN-0014'; Status = 'Teilweise integriert'; Evidence = 'theme.c: High Contrast mit opaken Flächen, Rahmen, gelbem Fokus, weißen Texten, Reduced Motion und Materialfallback; QEMU-Wechsel und visueller Nachweis; Screenreader fehlt' },
    @{ Pattern = 'NPSPEC-BOOTDESIGN-0015'; Status = 'Teilweise integriert'; Evidence = 'BIOS und UEFI verwenden dieselbe generierte 2-Bit-AA-NovaOS-Bildmarke, Nova-Blau und Wortmarke; UEFI Bootmanager spiegelt den Kopf spezifikationsgemäß nach rechts; vollständige visuelle BIOS/UEFI-Parität aller Themes fehlt' },
    @{ Pattern = 'NPSPEC-BOOTRESOURCE-0011'; Status = 'Teilweise integriert'; Evidence = 'Dark-, Light- und High-Contrast-Deskriptoren sind als geprüfte Theme-Ressourcen zentral registriert; externer BAP-Loader bleibt durch fehlendes Wire-Format blockiert' },
    @{ Pattern = 'NPSPEC-KERNELLOADER-0001'; Status = 'Integriert'; Evidence = 'boot2.asm: NKI-bevorzugte Erkennung sowie validiertes direktes ELF32-/ELF64-Laden; QEMU-Positiv- und Negativtests' },
    @{ Pattern = 'NPSPEC-KERNELENTRY-0001'; Status = 'Teilweise integriert'; Evidence = 'boot2.asm und kernel: definierter NBHP/BIB-Registerübergang und frühe Kernelvalidierung; UEFI-Kernelübergang fehlt' },
    @{ Pattern = 'NPSPEC-BOOT-0001-N'; Status = 'Teilweise integriert'; Evidence = 'BIOS Stage 1/2, versioniertes NBHP/BIB, NKI/ELF-Fallback, Fehlerpfade und erster UEFI-Plattformpfad' },
    @{ Pattern = 'NPSPEC-BOOTERROR-0001'; Status = 'Teilweise integriert'; Evidence = 'Einheitlicher Nova-Fehlerbildschirm für Boot- und Kernel-Fehler; vollständige Recovery-Backends fehlen' },
    @{ Pattern = 'NPSPEC-BOOTFS-0001'; Status = 'Teilweise integriert'; Evidence = 'Sektorbasierter read-only Kernelzugriff vorhanden; Dateisystemtreiber-Registry und NovaFS fehlen' },
    @{ Pattern = 'NPSPEC-BOOTGRAPHICS-0001'; Status = 'Teilweise integriert'; Evidence = 'BIOS-Framebuffer-Renderer und UEFI-GOP-Grundpfad; gemeinsame plattformneutrale Runtime fehlt' },
    @{ Pattern = 'NPSPEC-BOOTHANDOFF-0001'; Status = 'Teilweise integriert'; Evidence = 'TLV-basiertes NBHP/BIB wird im BIOS-Pfad aufgebaut und vom Kernel validiert; UEFI-Handoff fehlt' },
    @{ Pattern = 'NPSPEC-BOOTMANAGER-0001'; Status = 'Teilweise integriert'; Evidence = 'BIOS Bootmanager-Runtime, Entries, Auswahl und sichere Fallbacks; persistente Entry-Quellen fehlen' },
    @{ Pattern = 'NPSPEC-BOOTMEMORY-0001'; Status = 'Teilweise integriert'; Evidence = 'Statische Speicherbereiche, Grenzen und lokaler Schreibtest; allgemeine Memory-Map-/Pool-Runtime fehlt' },
    @{ Pattern = 'NPSPEC-BOOTPLATFORM-0001'; Status = 'Teilweise integriert'; Evidence = 'BIOS- und getesteter UEFI-GOP-Einstieg vorhanden; einheitliche Plattform-vtable fehlt' },
    @{ Pattern = 'NPSPEC-BOOTSTAGE1-0001'; Status = 'Integriert'; Evidence = 'boot1.asm: deterministischer 512-Byte-Stage-1-Lader mit Signatur, Fehlerpfad und fester Stage-2-Grenze' },
    @{ Pattern = 'NPSPEC-BOOTSTAGE2-0001'; Status = 'Teilweise integriert'; Evidence = 'boot2.asm: Loader, GUI, Diagnose und Handoff; modulare Ressourcenauslagerung ist durch BAP-Wire-Format blockiert' },
    @{ Pattern = 'NPSPEC-BOOTUI-0002'; Status = 'Teilweise integriert'; Evidence = 'runtime.c/main.c/ui.c: zentraler heapfreier Single-Thread-Runtime-Core mit strikt validierter Subsystemreihenfolge Memory, Platform, Graphics, Diagnostics, Configuration, Resources, Scene, Layout, Motion, Input und Renderer; feste 32er Taskqueue priorisiert Critical, Input, Rendering, Animation, Layout, Background und Idle deterministisch. Jeder produktive UEFI-Frame durchläuft exakt Input, Event Queue, Control, Application, Motion, Layout, Dirty Detection, Render Queue, Rendering, Compositor, Present und Diagnostics; ausgelassene Phasen werden verworfen. Hosttests prüfen Reihenfolge, Scheduler und Fehlerfälle, QEMU belegt Running und abgeschlossene Frames. Eine vollständige gemeinsame BIOS-Runtime, Touch-/Controllerprovider und reale Hardware-Performancezeitmessung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTUI-0003'; Status = 'Teilweise integriert'; Evidence = 'runtime.c/main.c/ui.c: deterministischer Lifecycle Created, Initializing, Loading Resources, Building Scene, Layout, Ready, Running, Suspended, Recovery, Shutdown und Destroyed mit Abweisung ungültiger Transitionen, Eingabesperre in Suspend/Recovery sowie sicherem GUI-Fehlerübergang in Recovery/Textfallback. F6 auf Diagnose testet produktiv Suspend/Resume und zeichnet den Statusframe; Hosttests decken Recovery, Shutdown und Destroy ab, QEMU-Marker und Framebuffer belegen Lifecycle und sichtbaren Endzustand. Echtes Firmware-Suspend/Resume, Hotplug-/Controllerpfade und identische BIOS-Lifecycle-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTUI-0007'; Status = 'Teilweise integriert'; Evidence = 'memory.c/ui.c/diagnostics.c: zentraler heapfreier Manager für Permanent/Runtime/Scene/Animation/Frame/Render/Cache/Diagnostics mit normativen Einzelbudgets und 64-MiB-Gesamtgrenze, getrennten statischen Arenen, O(1)-Bump-Allokation, 16-/64-Byte-Alignment, 256er Objektmetadaten, Owner, Referenzzählung, Pointer-/Double-Free-/Alignment-/Overflow-Erkennung, Peak/Fragmentierung und atomarem Frame-Reset. Der produktive Renderer reserviert und validiert Frame-Metadaten über den Manager; F8 zeigt den geprüften Zustand, Host erzwingt Cache-Overflow mit Safe Mode und QEMU belegt jeden Frame. Bereits ältere statische Subsystempools sind noch nicht vollständig migriert, UEFI-Seitenreservierung und BIOS-Parität fehlen' },
    @{ Pattern = 'NPSPEC-BOOTUI-0008'; Status = 'Teilweise integriert'; Evidence = 'recovery.c/ui.c/main.c: heapfreier Recovery Manager mit INFO/WARNING/RECOVERABLE/CRITICAL/FATAL, sieben deterministischen Eskalationsstufen, 32er Historie, Diagnoseevents, Feature-Isolation, Safe Mode, Textmodus, Continue-Boot-Invariante und sechs einmalig auslösenden Watchdogs. F10 auf Diagnose simuliert kritische Degradation mit verständlicher Statusmeldung; F9 prüft den fatalen Textfallback mit automatischem Fünf-Sekunden-Weiterstart. Hosttests und QEMU-Marker/Framebuffer belegen beide Pfade. Automatische Hooks für jeden einzelnen Renderer-/Resource-/Layoutfehler, echte GOP-Fehlerinjektion und BIOS-Parität fehlen' },
    @{ Pattern = 'NPSPEC-BOOTUI-0009'; Status = 'Teilweise integriert'; Evidence = 'configuration.c/ui.c/main.c: zentraler heapfreier Runtime-Manager mit Version 1.0.0, sicheren Defaults, expliziten Wertebereichen, interner Integritätsprüfsumme, O(1)-Key-Zugriff, atomarem Begin/Set/Commit, vollständigem Rollback, Reset, Generation/Benachrichtigung und getrennten temporären Overrides. Theme, Reduced Motion, Tooltips und 250..1500-ms-Verzögerung committen produktiv vor Anwendung; Hosttests prüfen Korruption und Transaktionen, Settings-/Theme-QEMU-Flows belegen mehrere Commits und sichtbare Endzustände. Das externe Binärformat bleibt nicht implementierbar definiert: Magic/Formatkennung, Headergröße, Feldoffsets, Endianness, Section-Typen, externer Prüfsummenalgorithmus und Migrationsabbildungen fehlen; deshalb wird keine inkompatible Persistenz erfunden' },
    @{ Pattern = 'NPSPEC-BOOTUI-'; Status = 'Teilweise integriert'; Evidence = 'BIOS-Runtime mit DLU, Zuständen, Eingabe, Fehlerpfaden und Tokens sowie UEFI-GOP-Grundpfad; gemeinsame Runtime/Pools fehlen' },
    @{ Pattern = 'NPSPEC-BOOTMANAGER-UI-0001'; Status = 'Teilweise integriert'; Evidence = 'BIOS und UEFI: Control-basierte Hauptauswahl, Icons, sichtbarer Fokus, Tastatur/Maus, Statuszeile und sicherer Standardstart; Multi-Boot-Discovery, Touch und vollständiges Informationspanel fehlen' },
    @{ Pattern = 'NPSPEC-BOOTMANAGER-UI-0002'; Status = 'Teilweise integriert'; Evidence = 'boot2.asm: BM_VIEW_DETAILS, F2, Eigenschaften-/Statusansicht und Start-/Erweitert-Aktionen; Motion und Touch fehlen' },
    @{ Pattern = 'NPSPEC-BOOTMANAGER-UI-0003'; Status = 'Teilweise integriert'; Evidence = 'boot2.asm: BM_VIEW_ADVANCED, F3, fokussierbare Startmodusliste, Recovery-/Fallback-Aktionen; Kernelparametereditor fehlt' },
    @{ Pattern = 'NPSPEC-BOOTMANAGER-UI-0004'; Status = 'Teilweise integriert'; Evidence = 'BIOS und UEFI: navigierbares Recovery-Menü, sichere Nicht-verfügbar-Zustände und Rücknavigation; geprüfte schreibende Recovery-Module fehlen' },
    @{ Pattern = 'NPSPEC-BOOTMANAGER-UI-0005'; Status = 'Teilweise integriert'; Evidence = 'boot2.asm: Self-Healing-Systemstatus und sichere Sperre schreibender Reparaturen; NovaFS-Reparaturmodul fehlt' },
    @{ Pattern = 'NPSPEC-BOOTMANAGER-UI-0006'; Status = 'Teilweise integriert'; Evidence = 'boot2.asm: Snapshot-Ansicht mit leerem, erklärtem Zustand; NovaFS-Snapshot-Katalog fehlt' },
    @{ Pattern = 'NPSPEC-BOOTMANAGER-UI-0007'; Status = 'Teilweise integriert'; Evidence = 'boot2.asm: Speichertestansicht, AA55/55AA-Schnelltest, Ergebnis und Fortschritt; vollständiger physischer RAM-Test fehlt' },
    @{ Pattern = 'NPSPEC-BOOTMANAGER-UI-0008'; Status = 'Teilweise integriert'; Evidence = 'boot2.asm: read-only BIOS-Datenträgerstatus; GPT/MBR-, SMART- und Schreibmodule fehlen' },
    @{ Pattern = 'NPSPEC-BOOTMANAGER-UI-0009'; Status = 'Teilweise integriert'; Evidence = 'boot2.asm: Verschlüsselungsstatus und sicher deaktivierte Authentifizierung ohne verschlüsseltes Volume; Crypto-/TPM-Backend fehlt' },
    @{ Pattern = 'NPSPEC-BOOTMANAGER-UI-0010'; Status = 'Teilweise integriert'; Evidence = 'boot2.asm: Netzwerk-Boot-Status und erklärter No-Adapter/No-Server-Zustand; PXE-UNDI-/DHCP-Backend fehlt' },
    @{ Pattern = 'NPSPEC-BOOTMANAGER-UI-0011'; Status = 'Teilweise integriert'; Evidence = 'firmware.c/main.c/ui.c und boot2.asm: eigene UEFI-Firmwarestatusseite mit Hersteller, Revision, SecureBoot, SetupMode und OsIndicationsSupported; BootToFwUi wird nur bei gemeldeter Unterstützung nach zweistufiger Bestätigung per Runtime Services gesetzt und in QEMU bis zum Reset nachgewiesen; ein Runtime-Services-Mocktest belegt zusätzlich die sichere Sperre ohne Capability; TPM/SMBIOS/ACPI-Details und BIOS-Setupwechsel fehlen' },
    @{ Pattern = 'NPSPEC-BOOTMANAGER-UI-0014'; Status = 'Teilweise integriert'; Evidence = 'BIOS und UEFI: read-only Diagnoseansicht mit Übersicht, Hardware-, Boot-, Speicher- und Ereignisbereichen; vollständige Hardwareprovider und Berichtsexport fehlen' },
    @{ Pattern = 'NPSPEC-BOOTMANAGER-UI-0015'; Status = 'Teilweise integriert'; Evidence = 'BIOS und UEFI: Energieauswahl mit expliziter zweiter Bestätigung; UEFI Shutdown/Restart über Runtime ResetSystem, sichere Sperre nicht verfügbarer Recovery-/Firmware-/Netzwerkziele; Touch fehlt' },
    @{ Pattern = 'NPSPEC-BOOTMANAGER-UI-0016'; Status = 'Teilweise integriert'; Evidence = 'BIOS und UEFI: sichtbarer, sekündlich aktualisierter Fünf-Sekunden-Countdown, Abbruch durch Eingabe und sicherer Standardstart; persistente Konfiguration fehlt' },
    @{ Pattern = 'NPSPEC-BOOTMANAGER-UI-0018'; Status = 'Teilweise integriert'; Evidence = 'BIOS und UEFI: F1-Hilfe, lokale Bedienhinweise, ESC-Rücknavigation und Fokuswiederherstellung; UEFI ergänzt einen festen lokalen Acht-Themen-Index, UTF-8-Suche, gefilterte Ergebnisnavigation, kontextbezogene Detaildialoge und QEMU-Nachweis; vollständige Lokalisierungsressource, Touch und BIOS-Suchparität fehlen' },
    @{ Pattern = 'NPSPEC-BOOTINPUT-'; Status = 'Teilweise integriert'; Evidence = 'BIOS: PS/2-Tastatur/Maus; input.c: gemeinsame O(1)-Eventqueue, Pointer Capture/Hit-Test, Fokus, Shortcuts und Repeat; UEFI: Tastatur und Simple Pointer mit Cursor, Auswahl, Klickaktion und Countdown-Abbruch; QEMU weist Pointer-Protokoll und Tastaturnavigation nach, headless HMP-Mausinjektion und Touch fehlen' },
    @{ Pattern = 'NPSPEC-BOOTLAYOUT-0001'; Status = 'Teilweise integriert'; Evidence = 'layout.c/ui.c: heapfreie Measure-/Arrange-/Finalize-Laufzeit, Invalidierung und ausschließlich berechnete Bounds; allgemeiner Containerbaum und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTLAYOUT-0006'; Status = 'Teilweise integriert'; Evidence = 'layout.c: Compact/Standard/Wide-Breakpoints, 3%-Safe-Area und adaptive Brand-/Panel-Anordnung; QEMU-Nachweis in drei echten GOP-Modi, Touch-/Rotationstest fehlt' },
    @{ Pattern = 'NPSPEC-BOOTLAYOUT-0007'; Status = 'Teilweise integriert'; Evidence = 'layout.c: deterministische Ganzzahlskalierung von 1000 bis 2000 sowie Accessibility-Untergrenze; Firmware-DPI ist mangels physischer Displaymetrik sicher auf 96 DPI gesetzt' },
    @{ Pattern = 'NPSPEC-BOOTLAYOUT-0008'; Status = 'Teilweise integriert'; Evidence = 'layout.c: zentrale nova_dlu_to_pixels-Rundung; Panel, Abstände, Radien, Icons und Textskalierung werden daraus abgeleitet; BIOS nutzt eigene kompatible DLU-Tokens' },
    @{ Pattern = 'NPSPEC-BOOTLAYOUT-0009'; Status = 'Teilweise integriert'; Evidence = 'layout.c: validierter Min/Preferred/Max-Constraint-Resolver mit deterministischem Fehlerzähler; vollständige verschachtelte Container-Priorisierung fehlt' },
    @{ Pattern = 'NPSPEC-BOOTLAYOUT-0010'; Status = 'Teilweise integriert'; Evidence = 'layout.c/text.c: Safe-Area, skalierte Textmessung, Ellipsis und Layoutklassen; Hosttests decken 640x480 bis 4K ab, UEFI-QEMU 800x600/1280x720/1920x1080' },
    @{ Pattern = 'NPSPEC-BOOTLAYOUT-'; Status = 'Teilweise integriert'; Evidence = 'layout.c/ui.c: DLU-basierte responsive UEFI-Layoutlaufzeit mit Safe Area und Constraints; BIOS-/UEFI-Parität ist noch offen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-PROGRESS-0001'; Status = 'Teilweise integriert'; Evidence = 'dialog.c/ui.c/motion.c: bestimmter und unbestimmter Progress, 0..1000-Range, Status-/Prozentdarstellung, Theme/High Contrast und QEMU-Abschlussflow; eigenständiges BIOS-Control fehlt' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-SPINNER-0001'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c/main.c: heapfreier Activity Indicator mit validiertem Start/Stop, Phase und Spinner-/Ring-/Dots-/Arc-Templates; die unbestimmte Diagnosephase nutzt produktiv den Spinner ohne numerischen Fortschrittsbalken; Hosttest deckt alle vier Stile ab, QEMU einen stabilen Activity-Frame; kontinuierliche Motion-Timeline und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-CARD-0001'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c/compositor.c: heapfreies Card-Container-Control mit sieben validierten Typen, rekursionssicherer Child-Gruppierung, Theme-Rahmen/Radien und semantischen Information/Warning/Error/Success-Akzenten; die produktive UEFI-Seitenkarte verwendet das Control auf der stabilen Basissurface; zentrale Glass-/Acrylic-Tints und Materialfallbacks sind vorhanden, eine eigene gekachelte Material-Layer sowie BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-TILE-0001'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c/main.c: heapfreies Boot Option Tile mit sieben validierten Typen, Titel/Beschreibung/Status/Aktion, Themefläche, semantischer Typmarkierung und eindeutigem Fokusrahmen; Recovery nutzt produktiv ein responsives 2x3-Grid mit Icons, Status, Maus, Enter/Space und zweidimensionaler Tastaturnavigation; Hosttest und QEMU-Frame/Aktivierung vorhanden; Touch/Controller, Tile-Motion und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-ICONBUTTON-0001'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c/icons.c: spezialisierter heapfreier Icon Button mit validiertem semantischem Icon-Token, Pflicht-Tooltip, Aktion, Accessibility, Hover/Fokus/Pressed/Disabled-Grundzuständen und Themefarben; der Breadcrumb-Root verwendet produktiv den zentrierten Home-Icon-Button mit Text, Pointer, Tab, Enter/Space und QEMU-Root-Reset-Nachweis; SVG-Primärquelle, Touch/Controller, Motion und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-SCROLLVIEW-0001'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c/main.c: heapfreies bidirektionales O(1)-Scrollmodell mit Viewport-/Contentmaßen, X/Y-Clamp und Scroll-Into-View; die Diagnoseansicht nutzt einen echten vierzeiligen vertikalen Viewport, rendert ausschließlich vollständige sichtbare Einträge und unterstützt Pfeile, Page Up/Down, Home/End, Mausrad und gekoppeltes Pointer-Dragging; QEMU-Frame nachgewiesen; Touch/Controller, Smooth Scroll und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-SCROLLBAR-0001'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c: fest an eine ScrollView gebundene horizontale/vertikale Scrollbar mit proportionaler Mindest-Thumbgröße, Track-Sprung, Drag-Zustand, Theme- und Accessibilitydaten; produktiver vertikaler Diagnose-Thumb und QEMU-Screenshot; Auto-Hide/Motion, Touch/Controller und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-PASSWORD-0001'; Status = 'Teilweise integriert'; Evidence = 'dialog.c/ui.c: UTF-8-Secret-Puffer, Maskierung, Längengrenze, codepointweises Löschen und volatile Speicherbereinigung; Cursor/Selection/Paste und Authentifizierungsbackend fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-SWITCH-0001'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c: typisierter Off/On-/Locked-/Busy-Zustand, rundes Track-/Knob-Rendering, Theme/High Contrast, Accessibility und echter Reduced-Motion-Switch in den UEFI-Einstellungen; Motion und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-SLIDER-0001'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c/main.c: produktiver Tooltip-Delay-Slider 250..1500 ms mit 250-ms-Schritten, Clamp, Wertlabel, Links/Rechts/Home/End, Enter/Space, Pointer-Drag, Theme, Accessibility und QEMU-Ablauftest; Touch/Controller, vertikale Variante und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-CHECKBOX-0001'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c/main.c: produktive unabhängige Tooltip-Checkbox mit Checked/Unchecked/Indeterminate-Grundmodell, Enter/Space/Pointer, Theme, Accessibility, exakt einer Änderung je Aktivierung und QEMU-Nachweis; Touch/Controller und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-STATUSBADGE-0001'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c: heapfreies nichtinteraktives StatusBadge mit Information/Success/Warning/Error/Critical/Neutral/Custom, semantischen Themefarben, optionalem Icon, Textfallback, Rundung, Rahmen und Accessibility; alle sechs Recovery-Tiles verwenden Badges produktiv, Hosttests decken Typen/Validierung ab und QEMU belegt Frame sowie Dark/Light/High Contrast. Motion, Live-Region-/Screenreader-Ausgabe und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-CONTEXTMENU-0001'; Status = 'Teilweise integriert'; Evidence = 'ui.c/main.c: exklusives heapfreies Context Menu am Ziel-Control, Safe-Area-Korrektur, Fokusfang, F2/Rechtsklick, Pfeile, Enter, Escape, Outside-Click und sichere Detail-/Optionsaktionen; Untermenüs, Touch und BIOS-Anbindung fehlen; QEMU-Frame und Aktion nachgewiesen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-TEXTFIELD-0001'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c/main.c: produktives UEFI-Hilfesuchfeld mit festem UTF-8-Puffer, Suchfilter, Placeholder, Fokus/Caret, Insert, Backspace, Delete, Links/Rechts/Home/End, Ergebnisaktualisierung, Pointer-Fokus, Accessibility, Themes, Host-Grenztests und vollständigem QEMU-Ablauf; virtuelle Tastatur, Pointer-Textselektion, Caret-Blinken und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-TOOLTIP-0001'; Status = 'Teilweise integriert'; Evidence = 'ui.c/main.c: genau ein zentraler Tooltip mit produktiv konfigurierbarer Aktivierung und 250..1500-ms-Verzögerung, Safe-Area-Positionierung, Theme/High Contrast, kein Fokus-/Input-Capture und sofortigem Ausblenden bei Eingabe, Dialog oder Context Menu; Motion/Touch und BIOS-Anbindung fehlen; QEMU-Frames visuell geprüft' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-BREADCRUMB-0001'; Status = 'Teilweise integriert'; Evidence = 'ui.c/main.c/navigation.c: Unterseiten zeigen Start/Chevron/aktuelle Seite; Start besitzt themebasierte Hover-/Fokuszustände, präzises Pointer-Hit-Testing und Tab/Enter/Space-Aktivierung; die zentrale Navigation setzt den Stack in O(1) auf Root zurück; tiefere Hierarchien, Touch/Controller und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-0003'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c: zentraler heapfreier 32er Style-Manager mit O(1)-ID-Zugriff/-Bindung, aufgelöster Vererbung, Override-Masken, Theme-Neubindung pro Control, semantischen Farbrollen, DLU-Geometrie und Opaque/Glass/Acrylic/Transparent; Dark/Light/High Contrast und Reduced Motion sind in QEMU belegt. Vollständige Typografie-, Effects-/Animationsdeskriptoren, Style-Diagnosezeiten, konsequente Entfernung aller lokalen Renderer-Geometrie sowie identische BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-0004'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c: zentraler heapfreier 64er Template-Manager mit statischem Standardtemplate für jeden Control-Typ, O(1)-Lookup/-Bindung, benannten Partmasken, Pflicht-Part-, Typ- und Rekursionsvalidierung sowie Template-Vererbung; jedes neu erzeugte Control erhält vor Nutzung ein validiertes kompatibles Template, Hosttests und produktiver UEFI-IMG-Frame belegen die Bindung. Ein vollständig renderergetriebener Visual Tree mit Partobjekten, ContentPresenter-Daten, Motion-/Accessibility-Metadaten und identische BIOS-Strukturen fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-0001'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c: heapfreier 128er Pool, Typen, Parent/Child, Lifecycle, Bounds, Dirty-State, Fokus, Hit-Test, exakt-einmal Aktionen, Styles, Accessibility, Werte und typisierte Renderer; Ereignisbubbling und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-0002'; Status = 'Teilweise integriert'; Evidence = 'controls.c: Haupt-, Sichtbarkeits-, Fokus-, Hover-, Pressed-, Selected-, Busy-, Error-, Checked-, Readonly- und Locked-Zustände mit validierten Übergängen und Diagnostik; Zustandsmotion und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTCONTROL-'; Status = 'Teilweise integriert'; Evidence = 'controls.c/ui.c und boot2.asm: gemeinsames typisiertes Controlmodell, datengetriebene Menüeinträge, Fokus, Icons/Text, Hit-Testing und sichere Fallbackdarstellung; spezialisierte Controls werden schrittweise angebunden' },
    @{ Pattern = 'NPSPEC-BOOTTEXT-'; Status = 'Teilweise integriert'; Evidence = 'boot-font-aa.inc; boot2.asm: bm_draw_text, bm_draw_text_wrapped, bm_measure_text' },
    @{ Pattern = 'NPSPEC-BOOTDESIGN-'; Status = 'Teilweise integriert'; Evidence = 'boot-ui-tokens.inc; boot2.asm: Theme-Tokens und Hochkontrastmodus' },
    @{ Pattern = 'NPSPEC-BOOTMANAGER-UI-'; Status = 'Teilweise integriert'; Evidence = 'boot2.asm: vollständiger BIOS-GUI-Pfad; uefi/main.c und bootmenu/ui.c: getesteter GOP-Menü- und Countdown-Grundpfad' },
    @{ Pattern = 'NPSPEC-BOOTDIALOG-0001'; Status = 'Teilweise integriert'; Evidence = 'dialog.c/ui.c: fester Dialogpool und -stack, vollständige Lifecycle-Reihenfolge, Typen, modale Root, Ergebnis und Ressourcenfreiheit; nichtmodale UEFI-Nutzung und BIOS-Parität fehlen' },
    @{ Pattern = 'NPSPEC-BOOTDIALOG-0002'; Status = 'Teilweise integriert'; Evidence = 'dialog.c/ui.c: genau ein aktiver modaler Dialog, Backdrop, Eingabesperre, Safe-Area-Zentrierung, Fokusfang und Escape-Abbruch; Touch fehlt' },
    @{ Pattern = 'NPSPEC-BOOTDIALOG-0003'; Status = 'Teilweise integriert'; Evidence = 'ui.c/compositor.c: abgerundete thematische Dialogfläche, Alpha-Backdrop sowie Glass/Acrylic-Fallback-Infrastruktur; echter Blur-Cache fehlt' },
    @{ Pattern = 'NPSPEC-BOOTDIALOG-0004'; Status = 'Teilweise integriert'; Evidence = 'dialog.c/main.c: Confirmation-Typ, fokussierbare Aktionen, eindeutiges Resultat und sichere Abbruchaktion; BIOS-Anbindung fehlt' },
    @{ Pattern = 'NPSPEC-BOOTDIALOG-0005'; Status = 'Teilweise integriert'; Evidence = 'ui.c/main.c: thematisch markierter Warning-Dialog für blockierte Recovery-, Firmware- und Neustartziele mit verständlichem Text' },
    @{ Pattern = 'NPSPEC-BOOTDIALOG-0006'; Status = 'Teilweise integriert'; Evidence = 'dialog.c/ui.c: Error-Typ, Fehlerfarbtoken und Ergebnisweg; fataler Nova-Fehlerbildschirm existiert separat, Retry-/Detailpfad fehlt' },
    @{ Pattern = 'NPSPEC-BOOTDIALOG-0007'; Status = 'Teilweise integriert'; Evidence = 'dialog.c/ui.c/main.c: sichtbarer bestimmter/unbestimmter Progress, Prozent, Statuswechsel, Abschluss und Close; Werte werden begrenzt, QEMU-Frame nachgewiesen; Task-/Restzeitbackend und BIOS-Parität fehlen' },
    @{ Pattern = 'NPSPEC-BOOTDIALOG-0008'; Status = 'Teilweise integriert'; Evidence = 'dialog.c/ui.c: statischer 128-Byte-Secret-Puffer, UTF-8-Eingabe, Maskierung, codepointweises Backspace, Boundsprüfung und volatile Nullung beim Close; kein Crypto-/TPM-Backend, daher sicher nicht im normalen Flow angefordert' },
    @{ Pattern = 'NPSPEC-BOOTDIALOG-0009'; Status = 'Teilweise integriert'; Evidence = 'dialog.c/ui.c: zyklischer interner Fokus, modale Pointer-Hit-Tests, gespeicherte Vorfokus-ID und Blockade des Hintergrunds; Screenreader/Touch fehlen' },
    @{ Pattern = 'NPSPEC-BOOTDIALOG-0010'; Status = 'Teilweise integriert'; Evidence = 'motion.c/main.c/ui.c: UEFI Enter/Exit mit 180-ms-Fade und 95-auf-100-Prozent-Scale, 150-ms-Reduced-Motion-Fade ohne Scale, finalem Fokus, sicherem Abbruch und stabil synchronisiertem QEMU-Frame; BIOS-Anbindung fehlt' },
    @{ Pattern = 'NPSPEC-BOOTDIALOG-0011'; Status = 'Teilweise integriert'; Evidence = 'dialog.c: genau ein typisiertes Resultat, O(1)-Close, Cancel-Regel und oberster-Dialog-Priorität; asynchroner Callback fehlt' },
    @{ Pattern = 'NPSPEC-BOOTDIALOG-0012'; Status = 'Teilweise integriert'; Evidence = 'dialog.c/main.c: zerstörerische Aktion erfordert nach Fokuswahl eine zweite explizite Bestätigung; QEMU weist Dialog-Arming und echtes ResetSystem-Shutdown nach' },
    @{ Pattern = 'NPSPEC-BOOTNAV-0001'; Status = 'Teilweise integriert'; Evidence = 'navigation.c/page.c/main.c: zentraler heapfreier Zustandscontroller, Navigation Tree, Stack, Fokus, Dialog-/Recovery-Priorität und Transitionen; alternative Eingabegeräte und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTNAV-0002'; Status = 'Teilweise integriert'; Evidence = 'navigation.c: spezifikationsgemäßer statischer 64er O(1)-Stack mit Push/Pop/Replace/Reset, Root-Schutz, vollständigem State und Diagnose; Dialogstack separat, Recovery als typisierter Zweig; BIOS-Anbindung fehlt' },
    @{ Pattern = 'NPSPEC-BOOTNAV-0003'; Status = 'Teilweise integriert'; Evidence = 'page.c/ui.c: feste 16-Page-/64-View-Pools, eindeutige Root-Bäume, strikte Lifecycle, Sichtbarkeit, Layoutboxen, Fokus/Accessibility, iterative Events, Zyklus-/ID-Prüfung und modale Dialog-Pages; QEMU-Aktivierung/-Restore belegt, BIOS-Anbindung fehlt' },
    @{ Pattern = 'NPSPEC-BOOTNAV-0004'; Status = 'Teilweise integriert'; Evidence = 'navigation.c/main.c: Dialog vor Page, O(1)-Back, Root-Schutz und Wiederherstellung von Seite/Auswahl/Fokus/Scroll/Kontext; Breadcrumb-Direktnavigation führt über den zentralen Controller und einen validierten O(1)-Root-Reset; Recovery-Unterstack ist noch nicht separat typisiert' },
    @{ Pattern = 'NPSPEC-BOOTNAV-0005'; Status = 'Teilweise integriert'; Evidence = 'navigation.c/main.c/ui.c: sichtbarer 32-DLU Slide+Fade für Push/Pop, spiegelbildliche Richtung, Cross-Fade für Replace, ruhiger Recovery-Fade, Fokus-Sperre und Reduced-Motion-Fade; QEMU weist transformierte Frames/Richtungen nach, BIOS-Parität fehlt' },
    @{ Pattern = 'NPSPEC-BOOTDIALOG-'; Status = 'Teilweise integriert'; Evidence = 'dialog.c/ui.c: gemeinsame heapfreie UEFI-Dialoglaufzeit; spezialisierte Backends und BIOS-Parität fehlen' },
    @{ Pattern = 'NPSPEC-BOOTNAV-'; Status = 'Teilweise integriert'; Evidence = 'navigation.c/main.c: UEFI-Navigation-Stack mit Zustandswiederherstellung; allgemeiner View-Tree und BIOS-Parität fehlen' },
    @{ Pattern = 'NPSPEC-BOOTRENDER-'; Status = 'Teilweise integriert'; Evidence = 'boot2.asm: Framebuffer-Primitiven, Alpha-Text, Rundungen und Clipping' },
    @{ Pattern = 'NPSPEC-BOOTCOMPOSITOR-'; Status = 'Teilweise integriert'; Evidence = 'compositor.c: feste Surface-/Layer-Pools, stabile Z-Sortierung, Alpha, Overlay/Modal, Damage Merge, Glass/Acrylic und Safe-Fallback; BIOS-Anbindung und echter Blur fehlen' },
    @{ Pattern = 'NPSPEC-BOOTMOTION-0007'; Status = 'Teilweise integriert'; Evidence = 'motion.c/navigation.c: zentrale Property-Timeline erzeugt gruppierte Offset-/Opacity-Transitionen, sperrt Fokus, unterstützt Cancel und Reduced Motion; Materialgruppen und BIOS-Anbindung fehlen' },
    @{ Pattern = 'NPSPEC-BOOTMOTION-0009'; Status = 'Teilweise integriert'; Evidence = 'main.c/ui.c/navigation.c: alle UEFI-Menüwechsel laufen über Exit/atomaren Stackwechsel/Enter; Push links, Pop rechts, Recovery/Replace Fade, deterministische Software-Keyframes und QEMU-Transformnachweis; BIOS-Anbindung fehlt' },
    @{ Pattern = 'NPSPEC-BOOTMOTION-'; Status = 'Teilweise integriert'; Evidence = 'motion.c: globale Millisekunden-Timeline, O(n)-Pool-Scheduler, Properties, Easing/Spring-Fallback, Transition/Dialog/Navigation/Fokus/Progress, Unterbrechung, Reduced Motion und Budget-Degradation; BIOS-Anbindung fehlt' },
    @{ Pattern = 'NPSPEC-BOOTRESOURCE-'; Status = 'Teilweise integriert'; Evidence = 'Statisch validierte Font-, Icon- und Logo-Ressourcen; BAP-Loader fehlt' },
    @{ Pattern = 'NPSPEC-BOOTDIAG-'; Status = 'Teilweise integriert'; Evidence = 'diagnostics.c: strukturierter 256er Ringpuffer, Schweregrade, Rendering-/Input-/Motion-/Resource-Snapshots, Frame-/Speicher-/Qualitätsmetriken und QEMU-Initialisierungsnachweis; persistenter Export fehlt' },
    @{ Pattern = 'NPSPEC-BOOTTEST-'; Status = 'Teilweise integriert'; Evidence = 'Makefile: BIOS-, Maus-, Theme-, UI-, Recovery-, Plattform-, UEFI-Autostart-, UEFI-Eventqueue/Navigation-, ELF- und Fehlertests' },
    @{ Pattern = 'NPSPEC-BOOTPERF-'; Status = 'Teilweise integriert'; Evidence = 'diagnostics.c: 16,67/33,33-ms-Framebudget, Teilzeiten, 32-MiB-Low-End-Speicherbudget, Peak/Cache/Pool, adaptive und feste Qualitätsprofile sowie Safe-Fallback; hardwarebasierte GPU/High-End-Erkennung fehlt' }
)

$rows = foreach ($file in $files) {
    $raw = Get-Content -LiteralPath $file.FullName -Raw -Encoding UTF8
    $relative = $file.FullName.Substring($root.Length + 1).Replace('\', '/')
    $id = [regex]::Match($file.BaseName, 'NPSPEC-[A-Z0-9-]+').Value.TrimEnd('-')
    if ([string]::IsNullOrWhiteSpace($id)) { continue }
    if ([string]::IsNullOrWhiteSpace($raw)) {
        [pscustomobject]@{ Id=$id; File=$relative; Status='Blockiert'; Evidence='Spezifikationsdatei ist leer' }
        continue
    }
    $rule = $evidenceRules | Where-Object { $id -like "$($_.Pattern)*" } | Select-Object -First 1
    if ($rule) {
        [pscustomobject]@{ Id=$id; File=$relative; Status=$rule.Status; Evidence=$rule.Evidence }
    } else {
        [pscustomobject]@{ Id=$id; File=$relative; Status='Prüfung offen'; Evidence='Noch keine explizite Implementierungszuordnung' }
    }
}

$lines = @(
    '# NovaOS Bootmanager NPSPEC-Abdeckung',
    '',
    "Erzeugt: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')",
    '',
    "Dokumente: $($rows.Count)",
    '',
    '| NPSPEC | Status | Implementierungsnachweis | Datei |',
    '|---|---|---|---|'
)
foreach ($row in $rows) {
    $lines += "| $($row.Id) | $($row.Status) | $($row.Evidence) | $($row.File) |"
}

$target = [IO.Path]::GetFullPath((Join-Path (Get-Location) $OutputFile))
$directory = Split-Path -Parent $target
if (-not (Test-Path -LiteralPath $directory)) { New-Item -ItemType Directory -Path $directory | Out-Null }
[IO.File]::WriteAllLines($target, $lines, [Text.UTF8Encoding]::new($false))

$rows | Group-Object Status | Sort-Object Name | ForEach-Object {
    Write-Host ("{0}: {1}" -f $_.Name, $_.Count)
}
Write-Host "Abdeckungsmatrix: $target"
