param(
    [string]$OutputPath = "boot/bootloader/include/boot-font-aa.inc"
)

$ErrorActionPreference = "Stop"
Add-Type -AssemblyName System.Drawing

$baseCharacters = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-./:|;()"
$characters = @($baseCharacters.ToCharArray()) + @(
    [char]0x00E4, [char]0x00F6, [char]0x00FC,
    [char]0x00C4, [char]0x00D6, [char]0x00DC,
    [char]0x00DF
)
$characterBytes = @{}
foreach ($character in $characters) {
    $characterBytes[$character] = [int][char]$character
}
$characterBytes[[char]0x00E4] = 0x84
$characterBytes[[char]0x00F6] = 0x94
$characterBytes[[char]0x00FC] = 0x81
$characterBytes[[char]0x00C4] = 0x8E
$characterBytes[[char]0x00D6] = 0x99
$characterBytes[[char]0x00DC] = 0x9A
$characterBytes[[char]0x00DF] = 0xE1
$cellWidth = 14
$cellHeight = 20
$bytesPerGlyph = [math]::Ceiling(($cellWidth * $cellHeight) / 4)

$font = [System.Drawing.Font]::new(
    "Segoe UI Semibold",
    15,
    [System.Drawing.FontStyle]::Regular,
    [System.Drawing.GraphicsUnit]::Pixel
)
$format = [System.Drawing.StringFormat]::GenericTypographic
$format.FormatFlags = $format.FormatFlags -bor [System.Drawing.StringFormatFlags]::MeasureTrailingSpaces

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("; Generated by scripts/generate-boot-font.ps1")
$lines.Add("; Segoe UI Semibold, 15 px, 2-bit grayscale coverage, four pixels per byte.")
$lines.Add("BM_FONT_WIDTH equ $cellWidth")
$lines.Add("BM_FONT_HEIGHT equ $cellHeight")
$lines.Add("BM_FONT_BYTES_PER_GLYPH equ $bytesPerGlyph")
$encodedCharacters = $characters | ForEach-Object {
    "0x{0:X2}" -f $characterBytes[$_]
}
$lines.Add("bm_font_characters: db " + ($encodedCharacters -join ",") + ",0")

$widths = [System.Collections.Generic.List[int]]::new()
$glyphRows = [System.Collections.Generic.List[string]]::new()

foreach ($character in $characters) {
    $bitmap = [System.Drawing.Bitmap]::new(
        $cellWidth,
        $cellHeight,
        [System.Drawing.Imaging.PixelFormat]::Format32bppArgb
    )
    $graphics = [System.Drawing.Graphics]::FromImage($bitmap)
    $graphics.Clear([System.Drawing.Color]::Transparent)
    $graphics.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::AntiAliasGridFit
    $graphics.DrawString(
        [string]$character,
        $font,
        [System.Drawing.Brushes]::White,
        [System.Drawing.PointF]::new(0, 0),
        $format
    )

    $measured = $graphics.MeasureString([string]$character, $font, 100, $format)
    $advance = [math]::Min($cellWidth, [math]::Max(4, [math]::Ceiling($measured.Width) + 1))
    $widths.Add($advance)

    $packed = [System.Collections.Generic.List[int]]::new()
    $current = 0
    $slot = 0
    for ($y = 0; $y -lt $cellHeight; $y++) {
        for ($x = 0; $x -lt $cellWidth; $x++) {
            $coverage = [math]::Min(3, [math]::Floor(($bitmap.GetPixel($x, $y).A + 42) / 85))
            $current = $current -bor ($coverage -shl ($slot * 2))
            $slot++
            if ($slot -eq 4) {
                $packed.Add($current)
                $current = 0
                $slot = 0
            }
        }
    }
    if ($slot -ne 0) {
        $packed.Add($current)
    }

    $hex = $packed | ForEach-Object { "0x{0:X2}" -f $_ }
    $glyphRows.Add("    db " + ($hex -join ",") + " ; $character")
    $graphics.Dispose()
    $bitmap.Dispose()
}

$lines.Add("bm_font_widths:")
$lines.Add("    db " + (($widths | ForEach-Object { $_.ToString() }) -join ","))
$lines.Add("bm_font_bitmap:")
$lines.AddRange($glyphRows)

$font.Dispose()
$outputDirectory = Split-Path -Parent $OutputPath
if ($outputDirectory) {
    New-Item -ItemType Directory -Force -Path $outputDirectory | Out-Null
}
[System.IO.File]::WriteAllLines((Join-Path (Get-Location) $OutputPath), $lines)
