param(
    [string]$LogoSource = "assets/nova-logo.svg",
    [string]$ReferenceSource = "assets/bootloader-reference.png",
    [string]$OutputPath = "boot/bootloader/include/nova-art.inc"
)

$ErrorActionPreference = "Stop"
Add-Type -AssemblyName System.Drawing

$inkscape = "C:\Program Files\Inkscape\bin\inkscapecom.com"
if (-not (Test-Path -LiteralPath $inkscape)) {
    throw "Inkscape wurde nicht unter '$inkscape' gefunden."
}

$temporaryLogo = Join-Path $env:TEMP "nova-logo-boot-raster.png"
& $inkscape $LogoSource --export-type=png "--export-filename=$temporaryLogo" --export-width=160 --export-height=150
if ($LASTEXITCODE -ne 0) {
    throw "Das Nova-Logo konnte nicht gerastert werden."
}

function Convert-ToDbLines {
    param([System.Collections.Generic.List[int]]$Bytes)
    $result = [System.Collections.Generic.List[string]]::new()
    for ($offset = 0; $offset -lt $Bytes.Count; $offset += 24) {
        $count = [math]::Min(24, $Bytes.Count - $offset)
        $values = for ($index = 0; $index -lt $count; $index++) {
            "0x{0:X2}" -f $Bytes[$offset + $index]
        }
        $result.Add("    db " + ($values -join ","))
    }
    return $result
}

$logo = [System.Drawing.Bitmap]::FromFile((Resolve-Path -LiteralPath $temporaryLogo))
$logoBytes = [System.Collections.Generic.List[int]]::new()
for ($y = 0; $y -lt 150; $y++) {
    for ($byteX = 0; $byteX -lt 40; $byteX++) {
        $packed = 0
        for ($slot = 0; $slot -lt 4; $slot++) {
            $pixel = $logo.GetPixel(($byteX * 4) + $slot, $y)
            $coverage = [math]::Min(3, [math]::Floor(($pixel.A + 42) / 85))
            $packed = $packed -bor ($coverage -shl ($slot * 2))
        }
        $logoBytes.Add($packed)
    }
}
$logo.Dispose()

# Exakter Ausschnitt des vom Benutzer entworfenen ;(-Symbols.
$reference = [System.Drawing.Bitmap]::FromFile((Resolve-Path -LiteralPath $ReferenceSource))
$mark = [System.Drawing.Bitmap]::new(82, 90, [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
$graphics = [System.Drawing.Graphics]::FromImage($mark)
$graphics.Clear([System.Drawing.Color]::Transparent)
$graphics.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
$graphics.PixelOffsetMode = [System.Drawing.Drawing2D.PixelOffsetMode]::HighQuality
$graphics.DrawImage(
    $reference,
    [System.Drawing.Rectangle]::new(0, 0, 82, 90),
    [System.Drawing.Rectangle]::new(75, 105, 105, 115),
    [System.Drawing.GraphicsUnit]::Pixel
)

$markBytes = [System.Collections.Generic.List[int]]::new()
for ($y = 0; $y -lt 90; $y++) {
    for ($byteX = 0; $byteX -lt 21; $byteX++) {
        $packed = 0
        for ($slot = 0; $slot -lt 4; $slot++) {
            $x = ($byteX * 4) + $slot
            $coverage = 0
            if ($x -lt 82) {
                $pixel = $mark.GetPixel($x, $y)
                $brightness = [math]::Max($pixel.R, [math]::Max($pixel.G, $pixel.B))
                $normalized = [math]::Max(0, [math]::Min(255, ($brightness - 20) * 255 / 235))
                $coverage = [math]::Min(3, [math]::Floor(($normalized + 42) / 85))
            }
            $packed = $packed -bor ($coverage -shl ($slot * 2))
        }
        $markBytes.Add($packed)
    }
}
$graphics.Dispose()
$mark.Dispose()
$reference.Dispose()

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("; Generated by scripts/generate-boot-art.ps1 from the checked-in UI sources.")
$lines.Add("NOVA_LOGO_WIDTH equ 160")
$lines.Add("NOVA_LOGO_HEIGHT equ 150")
$lines.Add("NOVA_LOGO_ROW_BYTES equ 40")
$lines.Add("NOVA_ERROR_MARK_WIDTH equ 82")
$lines.Add("NOVA_ERROR_MARK_HEIGHT equ 90")
$lines.Add("NOVA_ERROR_MARK_ROW_BYTES equ 21")
$lines.Add("nova_logo_bitmap:")
foreach ($line in (Convert-ToDbLines $logoBytes)) {
    $lines.Add([string]$line)
}
$lines.Add("nova_error_mark_bitmap:")
foreach ($line in (Convert-ToDbLines $markBytes)) {
    $lines.Add([string]$line)
}

$outputDirectory = Split-Path -Parent $OutputPath
if ($outputDirectory) {
    New-Item -ItemType Directory -Force -Path $outputDirectory | Out-Null
}
[System.IO.File]::WriteAllLines((Join-Path (Get-Location) $OutputPath), $lines)
Remove-Item -LiteralPath $temporaryLogo -Force
